SELECT * FROM BD_GENERAL.DBO.CURRENCY WHERE L_CURRENCY=1
SELECT * FROM BD_GENERAL.DBO.TERMS 

--	SELECT * FROM DATA_02PRUEBAS.DBO.users_pearl
--	SELECT en_num_emp FROM DATA_02PRUEBAS.DBO.users_pearl

SELECT * 
FROM HOWE.DBO.VISTA_GAFETES
inner JOIN DATA_02PRUEBAS.DBO.users_pearl on correo=EP_CORREO_ELECTRONICO
WHERE EN_SUPERVISOR='GERENTES'

-- AGREGAR COLUMNA # RELOJ A LA TABLA DE USUARIOS_PEARL
--ALTER TABLE DATA_02PRUEBAS.DBO.users_pearl
--ADD en_num_emp		int default 0

-- ELIMINAR COLUMNA # RELOJ A LA TABLA DE USUARIOS_PEARL
-- ALTER TABLE DATA_02PRUEBAS.DBO.users_pearl
-- DROP COLUMN en_num_emp


-- PARA INSERTAR LOS VALORES CORRESPONDIENTES
DECLARE @VP_CORREO VARCHAR(250)
DECLARE @VP_CODIGO INT
DECLARE @VP_NUM_EMPL INT

DECLARE CU_INSERT_NUM_EMPL CURSOR LOCAL FOR		
		SELECT	EN_NUM_EMP,
				EP_CORREO_ELECTRONICO 
		FROM	HOWE.DBO.VISTA_GAFETES
	
OPEN CU_INSERT_NUM_EMPL
	FETCH NEXT FROM CU_INSERT_NUM_EMPL INTO	@VP_NUM_EMPL, @VP_CORREO
	WHILE @@FETCH_STATUS = 0
	BEGIN
	
	SELECT	@VP_CODIGO=CODIGO
	FROM	DATA_02PRUEBAS.DBO.users_pearl
	WHERE	RTRIM(LTRIM(UPPER(correo)))=RTRIM(LTRIM(UPPER(@VP_CORREO)))

		IF @VP_CODIGO<>''
		BEGIN
			UPDATE	DATA_02PRUEBAS.DBO.users_pearl
			SET
					en_num_emp = @VP_NUM_EMPL
			WHERE	codigo=@VP_CODIGO
		END

	FETCH NEXT FROM CU_INSERT_NUM_EMPL INTO	@VP_NUM_EMPL, @VP_CORREO
	END
CLOSE		CU_INSERT_NUM_EMPL
DEALLOCATE	CU_INSERT_NUM_EMPL