-- ///////////////////////////////////////////////////////////////////
-- //	PARA REALIZAR LA MODIFICACIÓN DE PO CON ID TEMPORAL. 
-- //	SE REALIZA:
-- //	* ELIMINAR LLAVE PRIMARIA DE [HEADER_PURCHASE_ORDER]
-- //	* AGREGA TABLA DE ID´S TEMPORALES PARA PO
-- //	* AGREGA TABLA DE PO QUE QUEDARÁ COMO LIVE


-- ///////////////////////////////////////////////////////////////////

/*
-- ///////////////////////////////////////////////////////////////////
-- //			DROP PARA LAS PRIMAREY KEYS
-- ///////////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[DETAILS_PURCHASE_ORDER] 
	DROP CONSTRAINT [FK_HEADER_PURCHASE_ORDER_01]
GO

ALTER TABLE [dbo].[DETAILS_BLANKET_PURCHASE_ORDER]
	DROP CONSTRAINT [FK_HEADER_PURCHASE_ORDER_10] 
GO

ALTER TABLE [dbo].[HEADER_PURCHASE_ORDER]
	DROP CONSTRAINT [PK_HEADER_PURCHASE_ORDER]
GO

ALTER TABLE [dbo].[HEADER_PURCHASE_ORDER] 
	DROP	[FK_STATUS_PURCHASE_ORDER_01] 
GO
*/

-- ///////////////////////////////////////////////////////////////////
-- //	TABLA TEMPORAL PARA RELACIONAR LA PO CON UN ID PROVISIONAL
-- //	ESTA TABLA CONTENDRÁ EL ID QUE SERÁ EL DISPONIBLE PARA ASIGNAR
-- //					PURCHASE_ORDER_TEMP
-- ///////////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HEADER_PURCHASE_ORDER_TEMP]') AND type in (N'U'))
	DROP TABLE [dbo].[HEADER_PURCHASE_ORDER_TEMP]
GO
CREATE TABLE [dbo].[HEADER_PURCHASE_ORDER_TEMP] (
	[K_HEADER_PURCHASE_ORDER_TEMP]			[INT] IDENTITY (1,1)	NOT NULL,
--	[K_PO_TEMPORAL]							[VARCHAR](50) NOT NULL,
	[K_PO_TEMPORAL]							[INT] NOT NULL,
	[L_EN_USO]								[INT] DEFAULT 0				-- SI EL REGISTRO SE ENCUENTRA EN 0 SE PODRÁ USAR.
)	ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////
-- //	PARA AGREGAR LOS ID PROVISIONALES DE LA TABLA
-- //				CI - HEADER_PURCHASE_ORDER_TEMP
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_HEADER_PURCHASE_ORDER_TEMP]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_HEADER_PURCHASE_ORDER_TEMP]
GO
CREATE PROCEDURE [dbo].[PG_CI_HEADER_PURCHASE_ORDER_TEMP]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT
	-- ===========================
--	@PP_K_PO_TEMPORAL				VARCHAR (50)
AS				
	DECLARE @VP_CONTADOR INT=1
	-- ===========================
	
	WHILE @VP_CONTADOR<501
		BEGIN

			INSERT INTO HEADER_PURCHASE_ORDER_TEMP
					(	[K_PO_TEMPORAL]		)
			VALUES	
					--(	'T'+@PP_K_PO_TEMPORAL	)
					(	@VP_CONTADOR	)
		
			SET @VP_CONTADOR=@VP_CONTADOR+1
		END
GO

	EXECUTE [dbo].[PG_CI_HEADER_PURCHASE_ORDER_TEMP] 0,139
GO


-- SE AGREGAN LAS COLUMNAS A LA TABLAS PRINCIPALES PARA RELACIONAR LOS ID
ALTER TABLE [dbo].[HEADER_PURCHASE_ORDER]								
	ADD		[K_PO_TEMPORAL]				[INT] NOT NULL DEFAULT 0
GO		

ALTER TABLE [dbo].[DETAILS_PURCHASE_ORDER]
	ADD		[K_PO_TEMPORAL]				[INT] NOT NULL DEFAULT 0
GO

ALTER TABLE [dbo].[DETAILS_BLANKET_PURCHASE_ORDER]
	ADD		[K_PO_TEMPORAL]				[INT] NOT NULL DEFAULT 0
GO

ALTER TABLE [dbo].[PO_COMENTARIO_LOG]
	ADD		[K_PO_TEMPORAL]				[INT] NOT NULL DEFAULT 0
GO		

-- A ESTA TABLA NO ES NECESARIO AGREGARLE LA COLUMNA DE TEMPORAL YA QUE SÓLO SE PODRÁ RECIBIR MATERIAL DE UNA ORDEN IMPRESA
-- Y EN ESE MOMENTO YA LLEVA LA K_LIVE ASINADA

-- ALTER TABLE [dbo].[PO_PARTIAL_CLOSED_LOG]
-- 	DROP COLUMN		[K_PO_TEMPORAL]
-- GO		



/*
PARA BUSCAR EL ID DISPONIBLE PARA ASIGNAR DE MANERA PROVISIONAL

SELECT TOP (1) K_PO_TEMPORAL
FROM	HEADER_PURCHASE_ORDER_TEMP
WHERE	L_EN_USO=0
ORDER BY [K_HEADER_PURCHASE_ORDER_TEMP]

*/

-- ALTER TABLE [dbo].[HEADER_PURCHASE_ORDER]									
--	ALTER COLUMN [C_PURCHASE_ORDER]		[NVARCHAR](MAX)								--	AX:	20200903
-- ALTER TABLE [dbo].[HEADER_PURCHASE_ORDER]									
--	ALTER COLUMN [C_INFO_QUOTATION]		[NVARCHAR](MAX)								--	AX:	20200903
--	GO


--UPDATE	HEADER_PURCHASE_ORDER
--SET		K_PO_TEMPORAL=3,
--		K_HEADER_PURCHASE_ORDER=0
--WHERE	K_HEADER_PURCHASE_ORDER=137

--UPDATE	DETAILS_PURCHASE_ORDER
--SET		K_PO_TEMPORAL=3,
--		K_HEADER_PURCHASE_ORDER=0
--WHERE	K_HEADER_PURCHASE_ORDER=137


--UPDATE	[HEADER_PURCHASE_ORDER_TEMP]
--SET     [L_EN_USO]=1
--WHERE [K_PO_TEMPORAL]=3
