-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		COMPRAS
-- // MODULE:			HEADER_PURCHASE_ORDER
-- // OPERATION:		SP'S
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX DE LA ROSA			
-- // CREATION DATE:	20200206
-- ////////////////////////////////////////////////////////////// 

-- USE [COMPRAS]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_HEADER_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_HEADER_PURCHASE_ORDER]
GO
-- EXECUTE [dbo].[PG_LI_HEADER_PURCHASE_ORDER] 0,144,'',-1,-1,-1,null,null
-- EXECUTE [dbo].[PG_LI_HEADER_PURCHASE_ORDER] 0,139, '' , -1 , -1 , -1 , '2020-06-08' , '2020-07-10'
CREATE PROCEDURE [dbo].[PG_LI_HEADER_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_BUSCAR						VARCHAR(200),
	@PP_K_STATUS_PURCHASE_ORDER		INT,
	@PP_K_VENDOR					INT,
	@PP_K_CURRENCY					INT,
	@PP_F_INIT						DATE,
	@PP_F_FINISH					DATE
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	DECLARE @VP_L_APLICAR_MAX_ROWS	INT=1		
	DECLARE @VP_K_APPROVED_BY		INT
	DECLARE @VP_LI_N_REGISTROS		INT =5000
	-- ///////////////////////////////////////////
	-- =========================================		
	DECLARE @VP_K_FOLIO				INT
	EXECUTE [BD_GENERAL].DBO.[PG_RN_OBTENER_ID_X_REFERENCIA]			
								@PP_BUSCAR,	@OU_K_ELEMENTO = @VP_K_FOLIO	OUTPUT
-- =========================================		
	IF @VP_MENSAJE=''
	BEGIN
			SELECT	TOP (1)
			--SE OBTIENE LA K_GERENTE PARA LISTAR LAS ORDENES DEL MISMO DEPARTAMENTO.
			@VP_K_APPROVED_BY=
				(	CASE
						WHEN	EN_NUM_DEPT IN (1)			THEN	(7945)			-- RH					
						WHEN	EN_NUM_DEPT IN (2,5,6,11)	THEN	(22)			-- PRODUCCION
						WHEN	EN_NUM_DEPT IN (3)			THEN	(4475)			-- MATERIALES
						WHEN	EN_NUM_DEPT IN (4)			THEN	(1299)			-- CALIDAD
						WHEN	EN_NUM_DEPT IN (7,12)		THEN	(181)			-- PROYECTOS / SISTEMAS
						WHEN	EN_NUM_DEPT IN (8)			THEN	(67)			-- FINANZAS
						WHEN	EN_NUM_DEPT IN (9)			THEN	(52)
				END )
				FROM    BD_GENERAL.DBO.USUARIO_PEARL
				LEFT JOIN HOWE.DBO.VISTA_GAFETES ON EN_NUM_EMP=K_EMPLEADO_PEARL
				WHERE	L_BORRADO=0
				AND		USUARIO_PEARL.K_USUARIO_PEARL=@PP_K_USUARIO_ACCION

			IF @PP_K_USUARIO_ACCION=139	-- or @PP_K_USUARIO_ACCION=57
			BEGIN
				SET @VP_K_APPROVED_BY = -1
			END
	END
	-- =========================================		
	IF @VP_MENSAJE=''
	BEGIN
		--SET @VP_LI_N_REGISTROS = 0		
	SELECT		TOP (@VP_LI_N_REGISTROS)
				CONVERT(INTEGER,(TAX_RATE*100)) AS TAX,
				-- =============================	 
				F_DATE_PURCHASE_ORDER AS [DATE],
				F_REQUIRED_PURCHASE_ORDER AS [REQUIRED],
				F_PROMISE_PURCHASE_ORDER AS  [PROMISE],
				F_RECEIVED_PURCHASE_ORDER AS [RECEIVED],
				-- =============================	 
				S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
				D_VENDOR,
				S_PLACED_BY	, D_PLACED_BY,
				S_TERMS		, D_TERMS	 ,				
				S_CURRENCY	, D_CURRENCY,
				D_DELIVERY_PURCHASE_ORDER AS D_DELIVERY_TO,
				-- =============================	
				HEADER_PURCHASE_ORDER.*
				-- =============================	
	FROM		HEADER_PURCHASE_ORDER
	INNER JOIN 	STATUS_PURCHASE_ORDER	ON STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
	INNER JOIN 	VENDOR					ON VENDOR.K_VENDOR=HEADER_PURCHASE_ORDER.K_VENDOR
	INNER JOIN 	PLACED_BY				ON PLACED_BY.K_PLACED_BY=HEADER_PURCHASE_ORDER.K_PLACED_BY
	INNER JOIN	DELIVERY_PURCHASE_ORDER ON DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_DELIVERY_TO
	INNER JOIN 	BD_GENERAL.DBO.TERMS	ON TERMS.K_TERMS=HEADER_PURCHASE_ORDER.K_TERMS
	INNER JOIN 	BD_GENERAL.DBO.CURRENCY	ON CURRENCY.K_CURRENCY=HEADER_PURCHASE_ORDER.K_CURRENCY
				-- =============================
	WHERE		(	HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@VP_K_FOLIO
				OR	HEADER_PURCHASE_ORDER.ISSUED_BY_PURCHASE_ORDER			LIKE '%'+@PP_BUSCAR+'%'
				OR	HEADER_PURCHASE_ORDER.CONFIRMING_ORDER_WITH				LIKE '%'+@PP_BUSCAR+'%' 
--				OR	HEADER_PURCHASE_ORDER.DELIVERY_TO						LIKE '%'+@PP_BUSCAR+'%'
				OR	HEADER_PURCHASE_ORDER.C_PURCHASE_ORDER					LIKE '%'+@PP_BUSCAR+'%' )
				-- =============================
	AND			( @PP_F_INIT IS NULL		OR	@PP_F_INIT<=F_DATE_PURCHASE_ORDER)
	AND			( @PP_F_FINISH IS NULL		OR	@PP_F_FINISH>=F_DATE_PURCHASE_ORDER)
				-- =============================
	AND			( @PP_K_STATUS_PURCHASE_ORDER	=-1		OR	HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=@PP_K_STATUS_PURCHASE_ORDER )
	AND			( @PP_K_VENDOR =-1			OR	HEADER_PURCHASE_ORDER.K_VENDOR=@PP_K_VENDOR )
	AND			( @PP_K_CURRENCY =-1		OR	HEADER_PURCHASE_ORDER.K_CURRENCY=@PP_K_CURRENCY )
	AND			( @VP_K_APPROVED_BY =-1		OR	HEADER_PURCHASE_ORDER.K_APPROVED_BY=@VP_K_APPROVED_BY )
				-- =============================
	AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1
	ORDER BY	K_STATUS_PURCHASE_ORDER, F_DATE_PURCHASE_ORDER	DESC
	END
	-- /////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //	LISTADO PARA VERIFICAR LAS PO QUE SE DEBEN AUTORIZAR		--		LISTADO PARA GERENTES
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_APPROVE_MANAGER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_APPROVE_MANAGER]
GO
--		 EXECUTE [dbo].[PG_LI_APPROVE_MANAGER] 0,57,1		-- FABIOLA
--		 EXECUTE [dbo].[PG_LI_APPROVE_MANAGER] 0,47,1		-- MIKE
--		 EXECUTE [dbo].[PG_LI_APPROVE_MANAGER] 0,139,1		-- AX
--		 EXECUTE [dbo].[PG_LI_APPROVE_MANAGER] 0,60,1		-- LIC. ADRIANA
CREATE PROCEDURE [dbo].[PG_LI_APPROVE_MANAGER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_L_PO_FINANCES				INT
	-- ===========================
	--@PP_BUSCAR					VARCHAR(200),
	--@PP_K_STATUS_PURCHASE_ORDER	INT,
	--@PP_K_VENDOR					INT,
	--@PP_K_CURRENCY				INT,
	--@PP_F_INIT					DATE,
	--@PP_F_FINISH					DATE
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	DECLARE @VP_LI_N_REGISTROS		INT =5000
	-- ///////////////////////////////////////////	
	IF @PP_K_USUARIO_ACCION NOT IN(60)
	BEGIN
		SET @PP_L_PO_FINANCES=0
	END
	-- ///////////////////////////////////////////	
	IF @VP_MENSAJE=''
	BEGIN
		IF @PP_L_PO_FINANCES=0
		BEGIN
			SELECT		TOP (@VP_LI_N_REGISTROS)
						CONVERT(INTEGER,(TAX_RATE*100)) AS TAX,
						-- =============================	 
						F_DATE_PURCHASE_ORDER AS [DATE],
						F_REQUIRED_PURCHASE_ORDER AS [REQUIRED],
						F_PROMISE_PURCHASE_ORDER AS  [PROMISE],
						F_RECEIVED_PURCHASE_ORDER AS [RECEIVED],
						-- =============================	 
						S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
						D_VENDOR,
						S_PLACED_BY	, D_PLACED_BY,
						S_TERMS		, D_TERMS	 ,				
						S_CURRENCY	, D_CURRENCY,
						D_DELIVERY_PURCHASE_ORDER AS D_DELIVERY_TO,
						HEADER_PURCHASE_ORDER.*
						-- =============================	
			FROM		HEADER_PURCHASE_ORDER
			INNER JOIN 	STATUS_PURCHASE_ORDER	ON STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
			INNER JOIN 	VENDOR					ON VENDOR.K_VENDOR=HEADER_PURCHASE_ORDER.K_VENDOR
			INNER JOIN 	PLACED_BY				ON PLACED_BY.K_PLACED_BY=HEADER_PURCHASE_ORDER.K_PLACED_BY
			INNER JOIN	DELIVERY_PURCHASE_ORDER ON DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_DELIVERY_TO
			INNER JOIN 	BD_GENERAL.DBO.TERMS	ON TERMS.K_TERMS=HEADER_PURCHASE_ORDER.K_TERMS
			INNER JOIN 	BD_GENERAL.DBO.CURRENCY	ON CURRENCY.K_CURRENCY=HEADER_PURCHASE_ORDER.K_CURRENCY
			INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL	ON HEADER_PURCHASE_ORDER.K_APPROVED_BY=USUARIO_PEARL.K_EMPLEADO_PEARL
						-- =============================
			WHERE		USUARIO_PEARL.K_USUARIO_PEARL=@PP_K_USUARIO_ACCION
						-- =============================
			AND			( HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER	=	2 )
			AND			HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER<>7
						-- =============================
			AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1
			ORDER BY	K_STATUS_PURCHASE_ORDER, F_DATE_PURCHASE_ORDER	DESC
		END
		ELSE IF @PP_L_PO_FINANCES=1
		BEGIN
			SELECT		TOP (@VP_LI_N_REGISTROS)
						CONVERT(INTEGER,(TAX_RATE*100)) AS TAX,
						F_DATE_PURCHASE_ORDER AS [DATE],
						F_REQUIRED_PURCHASE_ORDER AS [REQUIRED],
						S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
						D_VENDOR,
						S_PLACED_BY	, D_PLACED_BY,
						S_TERMS		, D_TERMS	 ,				
						S_CURRENCY	, D_CURRENCY,
						D_DELIVERY_PURCHASE_ORDER AS D_DELIVERY_TO,
						HEADER_PURCHASE_ORDER.*
						-- =============================	
			FROM		HEADER_PURCHASE_ORDER
			INNER JOIN 	STATUS_PURCHASE_ORDER	ON STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
			INNER JOIN 	VENDOR					ON VENDOR.K_VENDOR=HEADER_PURCHASE_ORDER.K_VENDOR
			INNER JOIN 	PLACED_BY				ON PLACED_BY.K_PLACED_BY=HEADER_PURCHASE_ORDER.K_PLACED_BY
			INNER JOIN	DELIVERY_PURCHASE_ORDER ON DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_DELIVERY_TO
			INNER JOIN 	BD_GENERAL.DBO.TERMS	ON TERMS.K_TERMS=HEADER_PURCHASE_ORDER.K_TERMS
			INNER JOIN 	BD_GENERAL.DBO.CURRENCY	ON CURRENCY.K_CURRENCY=HEADER_PURCHASE_ORDER.K_CURRENCY
			INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL	ON HEADER_PURCHASE_ORDER.K_APPROVED_BY=USUARIO_PEARL.K_EMPLEADO_PEARL
						-- =============================
			--WHERE		USUARIO_PEARL.K_USUARIO_PEARL=@PP_K_USUARIO_ACCION
						-- =============================
			WHERE		HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER	IN	(2,7)
						-- =============================
			AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1
			ORDER BY	K_STATUS_PURCHASE_ORDER, F_DATE_PURCHASE_ORDER	DESC			
		END
	END
	-- /////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //	LISTADO PARA VERIFICAR LAS PO QUE SE DEBEN AUTORIZAR		--		LISTADO PARA FINANZAS
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_APPROVE_FINANCES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_APPROVE_FINANCES]
GO
--		 EXECUTE [dbo].[PG_LI_APPROVE_FINANCES] 0,57,		11		-- FABIOLA
--		 EXECUTE [dbo].[PG_LI_APPROVE_FINANCES] 0,47		2		-- MIKE
--		 EXECUTE [dbo].[PG_LI_APPROVE_FINANCES] 0,139,		-1		-- AX
--		 EXECUTE [dbo].[PG_LI_APPROVE_FINANCES] 0,60		2		-- LIC. ADRIANA
CREATE PROCEDURE [dbo].[PG_LI_APPROVE_FINANCES]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	--@PP_BUSCAR						VARCHAR(200),
	@PP_K_STATUS_PURCHASE_ORDER		INT
	--@PP_K_VENDOR					INT,
	--@PP_K_CURRENCY					INT,
	--@PP_F_INIT						DATE,
	--@PP_F_FINISH					DATE
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	DECLARE @VP_LI_N_REGISTROS		INT =5000
	-- ///////////////////////////////////////////	

	IF @PP_K_STATUS_PURCHASE_ORDER<>-1
		BEGIN
		SELECT		TOP (@VP_LI_N_REGISTROS)
					CONVERT(INTEGER,(TAX_RATE*100)) AS TAX,
					-- =============================	 
					F_DATE_PURCHASE_ORDER AS [DATE],
					F_REQUIRED_PURCHASE_ORDER AS [REQUIRED],
					F_PROMISE_PURCHASE_ORDER AS  [PROMISE],
					F_RECEIVED_PURCHASE_ORDER AS [RECEIVED],
					-- =============================	
					S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
					D_VENDOR,
					S_PLACED_BY	, D_PLACED_BY,
					S_TERMS		, D_TERMS	 ,				
					S_CURRENCY	, D_CURRENCY,
					D_DELIVERY_PURCHASE_ORDER AS D_DELIVERY_TO,
					HEADER_PURCHASE_ORDER.*
					-- =============================	
		FROM		HEADER_PURCHASE_ORDER
		INNER JOIN 	STATUS_PURCHASE_ORDER	ON STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
		INNER JOIN 	VENDOR					ON VENDOR.K_VENDOR=HEADER_PURCHASE_ORDER.K_VENDOR
		INNER JOIN 	PLACED_BY				ON PLACED_BY.K_PLACED_BY=HEADER_PURCHASE_ORDER.K_PLACED_BY
		INNER JOIN	DELIVERY_PURCHASE_ORDER ON DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_DELIVERY_TO
		INNER JOIN 	BD_GENERAL.DBO.TERMS	ON TERMS.K_TERMS=HEADER_PURCHASE_ORDER.K_TERMS
		INNER JOIN 	BD_GENERAL.DBO.CURRENCY	ON CURRENCY.K_CURRENCY=HEADER_PURCHASE_ORDER.K_CURRENCY
--		INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL	ON HEADER_PURCHASE_ORDER.K_APPROVED_BY=USUARIO_PEARL.K_EMPLEADO_PEARL
					-- =============================
		--WHERE		HEADER_PURCHASE_ORDER.K_APPROVED_BY=@PP_K_USUARIO_ACCION
		WHERE		@PP_K_USUARIO_ACCION IN (57,139)
					-- =============================
		AND			HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER	IN	(4,6,7,9,11,13)
					-- =============================
		AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1
		ORDER BY	K_STATUS_PURCHASE_ORDER, F_DATE_PURCHASE_ORDER	DESC
	END
	ELSE
	BEGIN
		SELECT		TOP (@VP_LI_N_REGISTROS)
					CONVERT(INTEGER,(TAX_RATE*100)) AS TAX,
					-- =============================	 
					F_DATE_PURCHASE_ORDER AS [DATE],
					F_REQUIRED_PURCHASE_ORDER AS [REQUIRED],
					F_PROMISE_PURCHASE_ORDER AS  [PROMISE],
					F_RECEIVED_PURCHASE_ORDER AS [RECEIVED],
					-- =============================	
					S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
					D_VENDOR,
					S_PLACED_BY	, D_PLACED_BY,
					S_TERMS		, D_TERMS	 ,				
					S_CURRENCY	, D_CURRENCY,
					D_DELIVERY_PURCHASE_ORDER AS D_DELIVERY_TO,
					HEADER_PURCHASE_ORDER.*
					-- =============================	
		FROM		HEADER_PURCHASE_ORDER
		INNER JOIN 	STATUS_PURCHASE_ORDER	ON STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
		INNER JOIN 	VENDOR					ON VENDOR.K_VENDOR=HEADER_PURCHASE_ORDER.K_VENDOR
		INNER JOIN 	PLACED_BY				ON PLACED_BY.K_PLACED_BY=HEADER_PURCHASE_ORDER.K_PLACED_BY
		INNER JOIN	DELIVERY_PURCHASE_ORDER ON DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER=HEADER_PURCHASE_ORDER.K_DELIVERY_TO
		INNER JOIN 	BD_GENERAL.DBO.TERMS	ON TERMS.K_TERMS=HEADER_PURCHASE_ORDER.K_TERMS
		INNER JOIN 	BD_GENERAL.DBO.CURRENCY	ON CURRENCY.K_CURRENCY=HEADER_PURCHASE_ORDER.K_CURRENCY
--		INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL	ON HEADER_PURCHASE_ORDER.K_APPROVED_BY=USUARIO_PEARL.K_EMPLEADO_PEARL
					-- =============================
		--WHERE		HEADER_PURCHASE_ORDER.K_APPROVED_BY=@PP_K_USUARIO_ACCION
		WHERE		@PP_K_USUARIO_ACCION IN (57,139)
					-- =============================
		--AND			HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=@PP_K_STATUS_PURCHASE_ORDER
		AND			( @PP_K_STATUS_PURCHASE_ORDER=-1	 OR		HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=@PP_K_STATUS_PURCHASE_ORDER )
					-- =============================
		AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1
		ORDER BY	K_STATUS_PURCHASE_ORDER, F_DATE_PURCHASE_ORDER	DESC
	END
	-- /////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_HEADER_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_HEADER_PURCHASE_ORDER]
GO
-- EXECUTE [dbo].[PG_SK_HEADER_PURCHASE_ORDER] 0,139,38
-- EXECUTE [dbo].[PG_SK_HEADER_PURCHASE_ORDER] 0,139,32
-- EXECUTE [dbo].[PG_SK_HEADER_PURCHASE_ORDER] 0,139,7
-- EXECUTE [dbo].[PG_SK_HEADER_PURCHASE_ORDER] 0,139,8008
-- EXECUTE [dbo].[PG_SK_DETAILS_PURCHASE_ORDER] 0,139,7
CREATE PROCEDURE [dbo].[PG_SK_HEADER_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		INT
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''	
	-- ///////////////////////////////////////////			
	SELECT		TOP (1)
				-- ===========================	-- ===========================
				-- PARA BLANKET PO
				L_IS_BLANKET					AS L_IS_BLANKET_PO,
				ISNULL(K_CUSTOMER,0)			AS K_CUSTOMER,
				ISNULL(D_PROGRAM,'')			AS D_PROGRAM			,
				ISNULL(ANNUAL_VOLUME,0)			AS ANNUAL_VOLUME		,
				ISNULL(GROSS_VEHICLE_AREA,0)	AS GROSS_VEHICLE_AREA	,
				-- ===========================	-- ===========================
				S_STATUS_PURCHASE_ORDER	, D_STATUS_PURCHASE_ORDER,
				D_VENDOR,
				S_PLACED_BY	, D_PLACED_BY,
				S_CURRENCY	, D_CURRENCY,	
				S_TERMS		, D_TERMS	 , C_TERMS	 ,
				-- ===========================	-- ===========================				
				--(CASE	
				--	WHEN	HEADER_PURCHASE_ORDER.K_TERMS=2 
				--	AND		(VENDOR.N_CREDIT_DAYS>0 
				--			--OR VENDOR.N_CREDIT_DAYS<>'') THEN	CONVERT(VARCHAR(5),VENDOR.[N_CREDIT_DAYS]) +' Día(s)/Day(s)'	-- ASI IBA A SER PARA NORMAL PERO NO FUNCIONA
				--			OR VENDOR.N_CREDIT_DAYS<>'') THEN	'NET ' + CONVERT(VARCHAR(5),VENDOR.[N_CREDIT_DAYS]) +' Days'	-- ASI LO QUIERE OMAR
				--	ELSE	''
				--END	) AS CREDIT_DAYS,
				-- ===========================	-- ===========================				
				(CASE	
					WHEN K_DELIVERY_TO IN (3) THEN	D_DELIVERY_TO
					ELSE	D_DELIVERY_PURCHASE_ORDER 
				END	) AS D_DELIVERY_TO,							
				-- ===========================	-- ===========================
				--D_DELIVERY_PURCHASE_ORDER	AS D_DELIVERY_TO,
				C_DELIVERY_PURCHASE_ORDER	AS C_DELIVERY_TO,
				S_DELIVERY_PURCHASE_ORDER	AS S_DELIVERY_TO,
				CONVERT(INTEGER,TAX_RATE*100) AS TAX_RATE_PER,
				-- ===========================	-- ===========================
				CONVERT(VARCHAR, CAST(SUBTOTAL_PURCHASE_ORDER AS MONEY), 2)	AS SUBTOTAL_PURCHASE_ORDER,
				--CAST(ADDITIONAL_TAXES_PURCHASE_ORDER AS MONEY)			AS OTHER_CHARGES_PURCHASE_ORDER,
				--CAST(ADDITIONAL_DISCOUNTS_PURCHASE_ORDER AS MONEY)		AS DISCOUNTS_PURCHASE_ORDER,
				CONVERT(VARCHAR, CAST(IVA_PURCHASE_ORDER AS MONEY), 2)		AS IVA_PURCHASE_ORDER,
				CONVERT(VARCHAR, CAST(TOTAL_PURCHASE_ORDER AS MONEY), 2)	AS TOTAL_PURCHASE_ORDER,
				-- ===========================	-- ===========================
				-- ===========================	-- ===========================
				-- ===========================	-- ===========================
				---- PARA INSERTAR LOS NOMBRES DE LAS AUTORIZACIONES/APROBACIONES Y QUIEN GENERA.
				CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) AS APPROVED,
				---- PARA OBTENER LA RUTA DEL ARCHIVO DE LA FIRMA DIGITAL DEL GERENTE
				CONCAT(C_FIRMAS,D_FIRMAS,S_FIRMAS)	AS RUTA_FIRMA,
				-- ===========================	-- ===========================
				-- ===========================	-- ===========================
				-- ===========================	-- ===========================
				--(CASE	
				--	WHEN CAST(F_REQUIRED_PURCHASE_ORDER AS DATE)=CAST(F_DATE_PURCHASE_ORDER AS DATE) THEN	'ASAP'
				--	ELSE	F_REQUIRED_PURCHASE_ORDER 
				--END	) AS ASAP,
				HEADER_PURCHASE_ORDER.*
				-- =============================	
	FROM		HEADER_PURCHASE_ORDER,		STATUS_PURCHASE_ORDER, 
				VENDOR,						PLACED_BY,
				BD_GENERAL.DBO.TERMS,		BD_GENERAL.DBO.CURRENCY,
				DELIVERY_PURCHASE_ORDER,
				-- =============================
				-- =============================
				HOWE.DBO.VISTA_GAFETES,				-- PARA OBTENER EL NOMBRE DE LA PERSONA QUE AUTORIZARÁ LA PO
				BD_GENERAL.DBO.FIRMAS
				-- =============================
	LEFT JOIN	DETAILS_BLANKET_PURCHASE_ORDER		ON DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=K_HEADER_PURCHASE_ORDER
	AND			DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
				-- =============================
	WHERE		HEADER_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER=STATUS_PURCHASE_ORDER.K_STATUS_PURCHASE_ORDER
	AND			HEADER_PURCHASE_ORDER.K_VENDOR=VENDOR.K_VENDOR
	AND			HEADER_PURCHASE_ORDER.K_PLACED_BY=PLACED_BY.K_PLACED_BY
	AND			HEADER_PURCHASE_ORDER.K_TERMS=TERMS.K_TERMS
	AND			HEADER_PURCHASE_ORDER.K_DELIVERY_TO=DELIVERY_PURCHASE_ORDER.K_DELIVERY_PURCHASE_ORDER
	AND			HEADER_PURCHASE_ORDER.K_CURRENCY=CURRENCY.K_CURRENCY
				-- =============================
				-- =============================
	AND			EN_NUM_EMP=HEADER_PURCHASE_ORDER.K_APPROVED_BY
	AND			HEADER_PURCHASE_ORDER.K_APPROVED_BY=FIRMAS.K_FIRMAS
				-- =============================
--	AND			DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
				-- =============================
	AND			HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
	AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1		
	-- ////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_DETAILS_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_DETAILS_PURCHASE_ORDER]
GO
-- EXECUTE [dbo].[PG_SK_DETAILS_PURCHASE_ORDER] 0,139,33
CREATE PROCEDURE [dbo].[PG_SK_DETAILS_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		INT
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	DECLARE @VP_K_STATUS			INT
	-- ///////////////////////////////////////////
	SELECT		@VP_K_STATUS = K_STATUS_PURCHASE_ORDER
	FROM		HEADER_PURCHASE_ORDER
	WHERE		K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
	
	IF	@VP_K_STATUS IN (11)
	BEGIN
		SELECT		TOP (5000)
					K_PO_PRICE_LOG	AS K_PO_PRICE,
					S_CURRENCY,
					ITEM.K_CURRENCY,
					PART_NUMBER_ITEM_VENDOR,
					D_ITEM,
					-- ======================================================
					DETAILS_PURCHASE_ORDER.QUANTITY_ORDER		AS QUANTITY,					
					DETAILS_PURCHASE_ORDER.QUANTITY_ORDER		AS QUANTITY_RECEIVED,
					0											AS QUANTITY_PENDING,
					DETAILS_PURCHASE_ORDER.QUANTITY_PENDING		AS QUANTITY_PENDING_ORIGINAL,
					-- ======================================================
					DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM, --PRICE_ITEM,
					TOTAL_PRICE as TOTAL_ITEM,
					DETAILS_PURCHASE_ORDER.*
		FROM		DETAILS_PURCHASE_ORDER
		INNER JOIN	ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
		INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
		WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
		ORDER BY	K_DETAILS_PURCHASE_ORDER
	END
	ELSE IF	@VP_K_STATUS IN (13)
	BEGIN
		SELECT		TOP (5000)
					K_PO_PRICE_LOG	AS K_PO_PRICE,
					S_CURRENCY,
					ITEM.K_CURRENCY,
					PART_NUMBER_ITEM_VENDOR,
					D_ITEM,
					-- ======================================================
					DETAILS_PURCHASE_ORDER.QUANTITY_ORDER		AS QUANTITY,
					0											AS QUANTITY_RECEIVED,
					(DETAILS_PURCHASE_ORDER.QUANTITY_ORDER - DETAILS_PURCHASE_ORDER.QUANTITY_RECEIVED)		AS QUANTITY_PENDING,
					DETAILS_PURCHASE_ORDER.QUANTITY_RECEIVED	AS QUANTITY_PENDING_ORIGINAL,
					-- ======================================================
					DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM, --PRICE_ITEM,
					TOTAL_PRICE as TOTAL_ITEM,
					DETAILS_PURCHASE_ORDER.*
		FROM		DETAILS_PURCHASE_ORDER
		INNER JOIN	ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
		INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
		WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
		ORDER BY	K_DETAILS_PURCHASE_ORDER
--		AND			DETAILS_PURCHASE_ORDER.QUANTITY_RECEIVED<>0
	END
	ELSE
	BEGIN
		SELECT		TOP (5000)
					K_PO_PRICE_LOG	AS K_PO_PRICE,
					S_CURRENCY,
					ITEM.K_CURRENCY,
					PART_NUMBER_ITEM_VENDOR,
					D_ITEM,
					DETAILS_PURCHASE_ORDER.QUANTITY_ORDER AS QUANTITY,
					DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM, --PRICE_ITEM,
					TOTAL_PRICE as TOTAL_ITEM,
					DETAILS_PURCHASE_ORDER.*
		FROM		DETAILS_PURCHASE_ORDER
		INNER JOIN	ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
		INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
		WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
		ORDER BY	K_DETAILS_PURCHASE_ORDER
	END
	-- ////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
--EN_NUM_DEPT		DP_DESC_DEPTO					--EN_NUM_DEPT		DP_DESC_DEPTO
	--1				DEPTO 1    (ADMINISTRACION)			--2				DEPTO 2 (PRODUCCION)
	--3				DEPTO 3 (MATERIALES)				--4				DEPTO 4  (CONTROL DE CALIDAD)
	--5				INGENIERIA-MANTENIMIENTO			--6				PRODUCCION
	--7				SISTEMAS							--8				FINANZAS
	--9				GERENCIA							--10			NO EXISTE EL 10
	--11			PERFORACION							--12			INGENIERIA DE PROYECTOS	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_ISSUED]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_ISSUED]
GO
-- EXECUTE [dbo].[PG_SK_ISSUED] 0,139,139
-- EXECUTE [dbo].[PG_SK_ISSUED] 0,139,145
-- EXECUTE [dbo].[PG_SK_ISSUED] 0,139,42
CREATE PROCEDURE [dbo].[PG_SK_ISSUED]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_USUARIO				INT
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''	
	-- ///////////////////////////////////////////			
	SELECT	TOP (1)
			USUARIO_PEARL.K_USUARIO_PEARL AS K_USUARIO_ALTA,
			CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) AS ISSUED,
			(	CASE
					WHEN	EN_NUM_DEPT IN (1)			THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=1 AND 	EN_SUPERVISOR='GERENTES' AND EN_NUM_EMP=7945)	-- RH					
					WHEN	EN_NUM_DEPT IN (2,5,6,11)	THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=6 AND 	EN_SUPERVISOR='GERENTES')						-- PRODUCCION
					WHEN	EN_NUM_DEPT IN (3)			THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=3 AND 	EN_SUPERVISOR='GERENTES')						-- MATERIALES
					WHEN	EN_NUM_DEPT IN (4)			THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=4 AND 	EN_SUPERVISOR='GERENTES')						-- CALIDAD
					WHEN	EN_NUM_DEPT IN (7,12)		THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=12 AND EN_SUPERVISOR='GERENTES')					-- PROYECTOS / SISTEMAS
					WHEN	EN_NUM_DEPT IN (8)			THEN	(SELECT CONCAT(EP_NOMBRE,' ',EP_APELLIDO_PATERNO) FROM	HOWE.DBO.VISTA_GAFETES WHERE EN_NUM_DEPT=8 AND 	EN_SUPERVISOR='GERENTES')						-- FINANZAS
					WHEN	EN_NUM_DEPT IN (9)			THEN	'JORGE HOLGUIN'
					ELSE	'X'
			END )		APPROVED,
				--SE OBTIENE LA K_DEL GERENTE PARA OBTENER LA IMAGEN EN EL REPORTE DE LA PO
			(	CASE
					WHEN	EN_NUM_DEPT IN (1)			THEN	(7945)			-- RH					
					WHEN	EN_NUM_DEPT IN (2,5,6,11)	THEN	(22)			-- PRODUCCION
					WHEN	EN_NUM_DEPT IN (3)			THEN	(4475)			-- MATERIALES
					WHEN	EN_NUM_DEPT IN (4)			THEN	(1299)			-- CALIDAD
					WHEN	EN_NUM_DEPT IN (7,12)		THEN	(181)			-- PROYECTOS / SISTEMAS
					WHEN	EN_NUM_DEPT IN (8)			THEN	(67)			-- FINANZAS
					WHEN	EN_NUM_DEPT IN (9)			THEN	'JORGE HOLGUIN'
					ELSE	'X'
			END )		K_APPROVED,
			'JORGE HOLGUIN' AS AUTHORIZED
	FROM    BD_GENERAL.DBO.USUARIO_PEARL
	LEFT JOIN HOWE.DBO.VISTA_GAFETES ON EN_NUM_EMP=K_EMPLEADO_PEARL
	WHERE	L_BORRADO=0
	AND		USUARIO_PEARL.K_USUARIO_PEARL=@PP_K_USUARIO
	ORDER BY APELLIDO_PATERNO ASC
	-- ////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //	STORED PROCEDURE ---> REVIEW_ESTATUS		
-- //	CONSULTA LOS PERMISOS PARA SABER SI PUEDE ABRIR O 
-- //	EJECUTAR CIERTA ACCIÓN EN LA FORMA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_PERMISOS_PO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_PERMISOS_PO]
GO
--		 EXECUTE [dbo].[PG_SK_PERMISOS_PO] 0,62,6002
--		 EXECUTE [dbo].[PG_SK_PERMISOS_PO] 0,139,6002
CREATE PROCEDURE [dbo].[PG_SK_PERMISOS_PO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_GRUPO_APROBADOR			INT
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''	
	-- ///////////////////////////////////////////		
	SELECT		TOP (1)
				COUNT(K_USUARIO)	AS MENSAJE
				-- =============================	
	FROM		BD_GENERAL.DBO.GRUPO_APROBADOR
				-- =============================
	WHERE		K_USUARIO=@PP_K_USUARIO_ACCION
	AND			K_TIPO_GRUPO_APROBADOR=@PP_K_GRUPO_APROBADOR
	AND			K_ESTATUS_GRUPO_APROBADOR=1
	-- ////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //	STORED PROCEDURE ---> VERIFICAR ESTATUS A REVISAR
-- //	CONSULTA EN BASE AL USUARIO A QUE PO PODRÁ CAMBIAR EL ESTATUS
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_VERIFICAR_ESTATUS_PO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO]
GO
--		 EXECUTE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO] 0,62
--		 EXECUTE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO] 0,139
--		 EXECUTE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO] 0,145
--		 EXECUTE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO] 0,60,1
CREATE PROCEDURE [dbo].[PG_SK_VERIFICAR_ESTATUS_PO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_L_PO_FINANCES				INT,
	-- ===========================
	@PP_K_STATUS					INT
--	@OU_K_ESTATUS					INT		OUTPUT
AS
	DECLARE @VP_K_ESTATUS_A_REVISAR			INT=0
	DECLARE @VP_SP_EJECUTAR					VARCHAR(150)=''
	-- ///////////////////////////////////////////		
	--	(	CASE
	--														EMPLEADO			USUARIO
	--			WHEN	EN_NUM_DEPT IN (1)			THEN	(7945)			--	62		RH					
	--			WHEN	EN_NUM_DEPT IN (2,5,6,11)	THEN	(22)			--	44		PRODUCCION
	--			WHEN	EN_NUM_DEPT IN (3)			THEN	(4475)			--	56		MATERIALES
	--			WHEN	EN_NUM_DEPT IN (4)			THEN	(1299)			--	47		CALIDAD
	--			WHEN	EN_NUM_DEPT IN (7,12)		THEN	(181)			--	42		PROYECTOS / SISTEMAS
	--			WHEN	EN_NUM_DEPT IN (8)			THEN	(67)			--	60		FINANZAS
	--			WHEN	EN_NUM_DEPT IN (9)			THEN	(52)			--	43		GERENTE PLANTA
	--	END )
	IF @PP_K_USUARIO_ACCION IN (62,44,56,47,42,60,43)
		BEGIN
			--SET @VP_K_ESTATUS_A_REVISAR = 2
			--SET @VP_SP_EJECUTAR			= 'PG_LI_APPROVE_MANAGER'

			EXECUTE	[dbo].[PG_LI_APPROVE_MANAGER]	@PP_K_SISTEMA_EXE,	@PP_K_USUARIO_ACCION, @PP_L_PO_FINANCES
		END
														--	EMPLEADO	USUARIO		NOMBRE
	ELSE IF @PP_K_USUARIO_ACCION IN (57,139)			--	7658		57			FABIOLA
		BEGIN
			--SET @VP_K_ESTATUS_A_REVISAR = 4
			--SET @VP_SP_EJECUTAR			= 'PG_LI_APPROVE_FINANCES'
			
			EXECUTE	[dbo].[PG_LI_APPROVE_FINANCES]	@PP_K_SISTEMA_EXE,	@PP_K_USUARIO_ACCION, @PP_K_STATUS
		END
	--ELSE
	--	BEGIN
	--			SET @VP_K_ESTATUS_A_REVISAR = 0
	--	END

	--SET @OU_K_ESTATUS=@VP_K_ESTATUS_A_REVISAR
	--SELECT	@VP_SP_EJECUTAR, @VP_K_ESTATUS_A_REVISAR
	-- ////////////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> REVIEW_ESTATUS
-- // STORED PROCEDURE ---> BUSCA EL ULTIMO COMENTARIO REALIZADO 
-- // EN UNA PO Y LO MUESTRA EN LA FICHA AL USUARIO, SIRVE PARA CONOCER
-- // EL MOTIVO DEL RECHAZO DE UNA PO ESPECIALMENTE.
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_COMENTARIOS_LOG_PO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_COMENTARIOS_LOG_PO]
GO
-- EXECUTE [dbo].[PG_SK_COMENTARIOS_LOG_PO] 0,139,3
-- EXECUTE [dbo].[PG_SK_COMENTARIOS_LOG_PO] 0,139,5
CREATE PROCEDURE [dbo].[PG_SK_COMENTARIOS_LOG_PO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		INT
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''	
	-- ///////////////////////////////////////////			
	SELECT		TOP (1)
				ISNULL(PO_COMENTARIO_LOG.K_HEADER_PURCHASE_ORDER,'') AS K_HEADER_PURCHASE_ORDER,
				ISNULL(C_PO_COMENTARIO_LOG,'') AS COMENTARIO
				-- =============================	
	FROM		HEADER_PURCHASE_ORDER,
				PO_COMENTARIO_LOG
				-- =============================
	WHERE		PO_COMENTARIO_LOG.K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
	AND			PO_COMENTARIO_LOG.K_USUARIO=@PP_K_USUARIO_ACCION
	AND			HEADER_PURCHASE_ORDER.L_BORRADO<>1		
	-- ////////////////////////////////////////////////////////////////////
GO

	
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_HEADER_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_HEADER_PURCHASE_ORDER]
GO
-- EXECUTE [dbo].[PG_IN_HEADER_PURCHASE_ORDER]	0, 139,  'TEST' 
CREATE PROCEDURE [dbo].[PG_IN_HEADER_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_C_PURCHASE_ORDER					[VARCHAR](255),
	-- ============================
	@PP_F_DATE_PURCHASE_ORDER				[DATE],
	@PP_F_REQUIRED_PURCHASE_ORDER			[DATE],
	-- ============================
	@PP_ISSUED_BY_PURCHASE_ORDER			[VARCHAR] (150),
	@PP_REQUIRED_PURCHASE_ORDER				[VARCHAR] (150),
	@PP_K_PLACED_BY							[INT],
	@PP_K_APPROVED_BY						[INT],
	-- ============================
	@PP_K_DELIVERY_TO						[INT],
	@PP_D_DELIVERY_TO						[VARCHAR] (250),
	@PP_CONFIRMING_ORDER_WITH				[VARCHAR] (150),
	@PP_K_VENDOR							[INT],
	-- ============================
	@PP_K_TERMS								[INT],
	@PP_K_CURRENCY							[INT],
	@PP_TAX_RATE							[DECIMAL] (10,4),
	-- ============================
	@PP_SUBTOTAL_PURCHASE_ORDER				[DECIMAL] (10,4),
	@PP_IVA_PURCHASE_ORDER					[DECIMAL] (10,4),
	@PP_DISCOUNT_PURCHASE_ORDER				[DECIMAL] (10,4),
	@PP_TOTAL_PURCHASE_ORDER				[DECIMAL] (10,4),
	-----=====================================================
	--	PARA DETAILS_PURCHASE_ORDER
	@PP_ITEM_ARRAY							NVARCHAR(MAX),
	@PP_QUANTITY_ARRAY						NVARCHAR(MAX),
	@PP_PRICE_ARRAY							NVARCHAR(MAX),
	@PP_TOTAL_ARRAY							NVARCHAR(MAX),
	@PP_K_PO_PRICE							NVARCHAR(MAX),
	-----=====================================================
	@PP_TOTAL_ITEMS							[INT],
	-----=====================================================
	--	PARA BLANKET
	@PP_L_IS_BLANKET						[INT],
	@PP_K_CUSTOMER							[INT],
	@PP_D_PROGRAM							[VARCHAR](500),
	@PP_ANNUAL_VOLUME						[DECIMAL](10,4),
	@PP_GROSS_VEHICLE_AREA					[DECIMAL](10,4),
	-----=====================================================
	@PP_C_INFO_QUOTATION					[VARCHAR] (500),
	@PP_TERMS_HEADER						[VARCHAR] (500),
	-----=====================================================
	@PP_ADDITIONAL_TAXES_PURCHASE_ORDER		[DECIMAL](10,4)
AS			
DECLARE @VP_MENSAJE						VARCHAR(500) = ''
DECLARE @VP_K_HEADER_PURCHASE_ORDER		INT = 0;
DECLARE @VP_K_PO						INT = 0;
DECLARE @VP_K_STATUS					INT = 1;
BEGIN TRANSACTION 
BEGIN TRY
		-- /////////////////////////////////////////////////////////////////////
		DECLARE @VP_BD_NAME				VARCHAR(300) = ''
		IF	@PP_K_SISTEMA_EXE=0
		SET @VP_BD_NAME='COMPRAS_Pruebas'
		ELSE
		SET @VP_BD_NAME='COMPRAS'

		EXECUTE [BD_GENERAL].dbo.[PG_SK_CATALOGO_K_MAX_GET]		@PP_K_SISTEMA_EXE, @VP_BD_NAME,
																'HEADER_PURCHASE_ORDER', 'K_HEADER_PURCHASE_ORDER',
																@OU_K_TABLA_DISPONIBLE = @VP_K_HEADER_PURCHASE_ORDER	OUTPUT
	-- /////////////////////////////////////////////////////////////////////
	--SET @VP_K_PO = @VP_K_HEADER_PURCHASE_ORDER + 8006	-- VALOR PARA PRUEBAS, SE ESTABLECE PARA NO INICIAR LAS PO EN 1
	-- //////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		IF @PP_K_USUARIO_ACCION IN (62,44,56,47,42,60,43)
		BEGIN
			SET @VP_K_STATUS=4
		END
		IF @PP_K_TERMS<>2
		BEGIN
			SET @PP_TERMS_HEADER=''
		END
	--============================================================================
	--======================================INSERTAR EL HEADER_PURCHASE_ORDER
	--============================================================================
		INSERT INTO HEADER_PURCHASE_ORDER
			(	[K_HEADER_PURCHASE_ORDER],	[C_PURCHASE_ORDER],
				-- ============================
				[K_STATUS_PURCHASE_ORDER],				
				-- ============================
				[F_DATE_PURCHASE_ORDER],	[F_REQUIRED_PURCHASE_ORDER],			
				-- ============================
				[ISSUED_BY_PURCHASE_ORDER],	[REQUIRED_PURCHASE_ORDER],				
				[K_PLACED_BY],				[K_APPROVED_BY],
				-- ============================
				[K_DELIVERY_TO],			[D_DELIVERY_TO],
				[CONFIRMING_ORDER_WITH],	[K_VENDOR],
				-- ============================
				[K_TERMS],					[K_CURRENCY],							
				[TAX_RATE],					--[ADDITIONAL_TAXES_PURCHASE_ORDER],		
				--[ADDITIONAL_DISCOUNTS_PURCHASE_ORDER],	
				--[PREPAID_PURCHASE_ORDER],				
				-- ============================
				[TOTAL_ITEMS],
				[SUBTOTAL_PURCHASE_ORDER],	[ADDITIONAL_DISCOUNTS_PURCHASE_ORDER],
				[IVA_PURCHASE_ORDER],		[ADDITIONAL_TAXES_PURCHASE_ORDER],
				[TOTAL_PURCHASE_ORDER],				
				-- ============================
				--[K_ACCOUNT_PURCHASE_ORDER],
				[L_IS_BLANKET],				[C_INFO_QUOTATION],
				[TERMS_HEADER],
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
		VALUES	
			(	@VP_K_HEADER_PURCHASE_ORDER, 
				--@VP_K_PO,		-- VALOR PARA PRUEBAS, SE ESTABLECE PARA NO INICIAR LAS PO EN 1
				@PP_C_PURCHASE_ORDER, 
				-- ============================
				@VP_K_STATUS, --@PP_K_STATUS_PURCHASE_ORDER,				
				-- ============================
				@PP_F_DATE_PURCHASE_ORDER,		@PP_F_REQUIRED_PURCHASE_ORDER,
				-- ============================
				@PP_ISSUED_BY_PURCHASE_ORDER,	@PP_REQUIRED_PURCHASE_ORDER,				
				@PP_K_PLACED_BY,				@PP_K_APPROVED_BY,
				-- ============================
				@PP_K_DELIVERY_TO,				@PP_D_DELIVERY_TO,
				@PP_CONFIRMING_ORDER_WITH,		@PP_K_VENDOR,
				-- ============================
				@PP_K_TERMS,					@PP_K_CURRENCY,							
				(@PP_TAX_RATE/100),					--0, --@PP_ADDITIONAL_TAXES_PURCHASE_ORDER,		
				--0, --@PP_ADDITIONAL_DISCOUNTS_PURCHASE_ORDER,	
				--0, --@PP_PREPAID_PURCHASE_ORDER,				
				-- ============================
				@PP_TOTAL_ITEMS,
				@PP_SUBTOTAL_PURCHASE_ORDER,	@PP_DISCOUNT_PURCHASE_ORDER,	
				@PP_IVA_PURCHASE_ORDER,			@PP_ADDITIONAL_TAXES_PURCHASE_ORDER,
				@PP_TOTAL_PURCHASE_ORDER,				
				-- ============================
				--0, --@PP_K_ACCOUNT_PURCHASE_ORDER,
				@PP_L_IS_BLANKET,				@PP_C_INFO_QUOTATION,
				@PP_TERMS_HEADER,
				-- ============================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )

			IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='The HEADER_PURCHASE_ORDER was not inserted. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@VP_K_HEADER_PURCHASE_ORDER)+']'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END				
	END

	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE		[dbo].[PG_IN_DETAILS_PURCHASE_ORDER]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															-----=====================================================
															@VP_K_HEADER_PURCHASE_ORDER,
															@PP_ITEM_ARRAY,		@PP_QUANTITY_ARRAY,
															@PP_PRICE_ARRAY,	@PP_TOTAL_ARRAY,	@PP_K_PO_PRICE
	END

	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE		[dbo].[PG_INUP_DETAILS_BLANKET_PURCHASE_ORDER]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															-----=====================================================
															@VP_K_HEADER_PURCHASE_ORDER,	@PP_L_IS_BLANKET,	
															@PP_K_CUSTOMER,					@PP_D_PROGRAM,					
															@PP_ANNUAL_VOLUME,				@PP_GROSS_VEHICLE_AREA
	END

-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [Insert] at [HEADER_PURCHASE_ORDER]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // PARA INSERTAR LOS DETALLES DE LA ORDEN DE COMPRA
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_DETAILS_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_DETAILS_PURCHASE_ORDER]
GO
CREATE PROCEDURE [dbo].[PG_IN_DETAILS_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-----=====================================================
	@PP_K_HEADER_PURCHASE_ORDER				INT,
	@PP_ITEM_ARRAY							NVARCHAR(MAX),
	@PP_QUANTITY_ARRAY						NVARCHAR(MAX),
	@PP_PRICE_ARRAY							NVARCHAR(MAX),
	@PP_TOTAL_ARRAY							NVARCHAR(MAX),
	@PP_K_PO_PRICE_ARRAY					NVARCHAR(MAX)
	-----=====================================================
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	-----=====================================================				
	DECLARE @VP_K_DETAIL_PO	INT = 1
	
	DECLARE @VP_POSICION_ITEM	INT
	DECLARE @VP_POSICION_QTY	INT
	DECLARE @VP_POSICION_PRICE	INT 
	DECLARE @VP_POSICION_TOTAL	INT
	DECLARE @VP_POSICION_PO_PRICE	INT
	DECLARE @VP_VALOR_ITEM		VARCHAR(500)
	DECLARE @VP_VALOR_QTY		VARCHAR(500)
	DECLARE @VP_VALOR_PRICE		VARCHAR(500)
	DECLARE @VP_VALOR_TOTAL		VARCHAR(500)
	DECLARE @VP_VALOR_PO_PRICE		VARCHAR(500)
	--Colocamos un separador al final de los parametros para que funcione bien nuestro codigo
	SET	@PP_ITEM_ARRAY		= @PP_ITEM_ARRAY		+ '/'
	SET	@PP_QUANTITY_ARRAY	= @PP_QUANTITY_ARRAY	+ '/'
	SET	@PP_PRICE_ARRAY		= @PP_PRICE_ARRAY		+ '/'
	SET	@PP_TOTAL_ARRAY		= @PP_TOTAL_ARRAY		+ '/'
	SET	@PP_K_PO_PRICE_ARRAY		= @PP_K_PO_PRICE_ARRAY		+ '/'
	
	--Hacemos un bucle que se repite mientras haya separadores, patindex busca un patron en una cadena y nos devuelve su posicion
	WHILE patindex('%/%' , @PP_ITEM_ARRAY) <> 0
		BEGIN
			SELECT @VP_POSICION_ITEM	=	patindex('%/%' , @PP_ITEM_ARRAY		)
			SELECT @VP_POSICION_QTY		=	patindex('%/%' , @PP_QUANTITY_ARRAY	)
			SELECT @VP_POSICION_PRICE	=	patindex('%/%' , @PP_PRICE_ARRAY	)
			SELECT @VP_POSICION_TOTAL	=	patindex('%/%' , @PP_TOTAL_ARRAY	)
			SELECT @VP_POSICION_PO_PRICE=	patindex('%/%' , @PP_K_PO_PRICE_ARRAY	)

			--Buscamos la posicion de la primera y obtenemos los caracteres hasta esa posicion
			SELECT @VP_VALOR_ITEM		= LEFT(@PP_ITEM_ARRAY		, @VP_POSICION_ITEM		- 1)
			SELECT @VP_VALOR_QTY		= LEFT(@PP_QUANTITY_ARRAY	, @VP_POSICION_QTY		- 1)
			SELECT @VP_VALOR_PRICE		= LEFT(@PP_PRICE_ARRAY		, @VP_POSICION_PRICE	- 1)
			SELECT @VP_VALOR_TOTAL		= LEFT(@PP_TOTAL_ARRAY		, @VP_POSICION_TOTAL	- 1)
			SELECT @VP_VALOR_PO_PRICE	= LEFT(@PP_K_PO_PRICE_ARRAY	, @VP_POSICION_PO_PRICE	- 1)
		
					INSERT INTO DETAILS_PURCHASE_ORDER
						(
						[K_HEADER_PURCHASE_ORDER]		,
						[K_DETAILS_PURCHASE_ORDER]		,
						-- ============================	,
						[K_ITEM],						
						-- ============================
						[QUANTITY_ORDER],
						[QUANTITY_RECEIVED],
						[QUANTITY_PENDING],
						-- ============================
						[K_PO_PRICE_LOG],
						[UNIT_PRICE],		[TOTAL_PRICE]
						)
					VALUES
						(
						@PP_K_HEADER_PURCHASE_ORDER,
						@VP_K_DETAIL_PO,
						@VP_VALOR_ITEM,		
						-- ============================
						@VP_VALOR_QTY,
						0,
						@VP_VALOR_QTY,
						-- ============================
						@VP_VALOR_PO_PRICE,
						@VP_VALOR_PRICE,	@VP_VALOR_TOTAL
						)																		
													
			IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='The DETAIL_PURCHASE_ORDER was not inserted. [DETAIL#'+CONVERT(VARCHAR(10),@VP_VALOR_ITEM)+']'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END	

			--Reemplazamos lo procesado con nada con la funcion stuff
			SELECT @PP_ITEM_ARRAY		= STUFF(@PP_ITEM_ARRAY		, 1, @VP_POSICION_ITEM , '')
			SELECT @PP_QUANTITY_ARRAY	= STUFF(@PP_QUANTITY_ARRAY	, 1, @VP_POSICION_QTY  , '')
			SELECT @PP_PRICE_ARRAY		= STUFF(@PP_PRICE_ARRAY		, 1, @VP_POSICION_PRICE, '')
			SELECT @PP_TOTAL_ARRAY		= STUFF(@PP_TOTAL_ARRAY		, 1, @VP_POSICION_TOTAL, '')
			SELECT @PP_K_PO_PRICE_ARRAY	= STUFF(@PP_K_PO_PRICE_ARRAY, 1, @VP_POSICION_PO_PRICE, '')

			SET @VP_K_DETAIL_PO += 1
		END
	-- ////////////////////////////////////////////////////////////////
	-- ///////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // PARA INSERTAR LOS DETALLES DE LA BLANKET PO
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_INUP_DETAILS_BLANKET_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_INUP_DETAILS_BLANKET_PURCHASE_ORDER]
GO
CREATE PROCEDURE [dbo].[PG_INUP_DETAILS_BLANKET_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-----=====================================================
	@PP_K_HEADER_PURCHASE_ORDER		INT,
	-----=====================================================
	@PP_L_IS_BLANKET				[INT],
	@PP_K_CUSTOMER					[INT],
	@PP_D_PROGRAM					[VARCHAR](500),
	@PP_ANNUAL_VOLUME				[DECIMAL](10,4),
	@PP_GROSS_VEHICLE_AREA			[DECIMAL](10,4)
AS
	DECLARE @VP_MENSAJE				VARCHAR(300) = ''

	IF @PP_L_IS_BLANKET=1
	BEGIN
					INSERT INTO DETAILS_BLANKET_PURCHASE_ORDER
						(
						[K_HEADER_PURCHASE_ORDER],
						[K_CUSTOMER],					[D_PROGRAM]			,
						[ANNUAL_VOLUME],				[GROSS_VEHICLE_AREA]
						)
					VALUES
						(
						@PP_K_HEADER_PURCHASE_ORDER,
						@PP_K_CUSTOMER,					@PP_D_PROGRAM		,
						@PP_ANNUAL_VOLUME,				@PP_GROSS_VEHICLE_AREA
						)																		
													
			IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='The DETAIL_BLANKET_PO was not inserted. [PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END	
	END
	-- ///////////////////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT / FICHA
-- // PARA INSERTAR LOS COMENTARIOS EN EL LOG DE COMENTARIOS DE LA PO
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_COMENTARIOS_LOG_PO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_COMENTARIOS_LOG_PO]
GO
CREATE PROCEDURE [dbo].[PG_IN_COMENTARIOS_LOG_PO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		[INT],
	@PP_C_PO_COMENTARIO_LOG			[VARCHAR](255)
AS			
DECLARE @VP_MENSAJE				VARCHAR(500) = ''
DECLARE @VP_K_HEADER_PURCHASE_ORDER			INT = 0;		
DECLARE @VP_K_PO			INT = 0;		
BEGIN TRANSACTION 
BEGIN TRY
-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN		
		INSERT	INTO PO_COMENTARIO_LOG 
		(	[K_HEADER_PURCHASE_ORDER]
			,[C_PO_COMENTARIO_LOG]
			,[K_USUARIO]
			,[F_COMENTARIO]				)
		VALUES	
		(	@PP_K_HEADER_PURCHASE_ORDER,
			@PP_C_PO_COMENTARIO_LOG,
			@PP_K_USUARIO_ACCION,
			GETDATE()					)

			IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='The COMMENT was not inserted. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END				
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [Insert] at [COMMENT_HEADER_PURCHASE_ORDER]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / FICHA
-- // PARA ACTUALIZAR EL ENCABEZADO DE LA PO
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_HEADER_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_HEADER_PURCHASE_ORDER]
GO
--       EXECUTE [dbo].[PG_UP_HEADER_PURCHASE_ORDER] 0, 139,												
CREATE PROCEDURE [dbo].[PG_UP_HEADER_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER				[INT],
	@PP_C_PURCHASE_ORDER					[VARCHAR](255),
	-- ============================
	@PP_F_DATE_PURCHASE_ORDER				[DATE],
	@PP_F_REQUIRED_PURCHASE_ORDER			[DATE],
	-- ============================
	@PP_ISSUED_BY_PURCHASE_ORDER			[VARCHAR] (150),
	@PP_REQUIRED_PURCHASE_ORDER				[VARCHAR] (150),
	@PP_K_PLACED_BY							[INT],
	@PP_K_APPROVED_BY						[INT],
	-- ============================
	@PP_K_DELIVERY_TO						[INT],
	@PP_D_DELIVERY_TO						[VARCHAR] (250),
	@PP_CONFIRMING_ORDER_WITH				[VARCHAR] (150),
	@PP_K_VENDOR							[INT],
	-- ============================
	@PP_K_TERMS								[INT],
	@PP_K_CURRENCY							[INT],
	@PP_TAX_RATE							[DECIMAL] (10,4),
	-- ============================
	@PP_SUBTOTAL_PURCHASE_ORDER				[DECIMAL] (10,4),
	@PP_IVA_PURCHASE_ORDER					[DECIMAL] (10,4),
	@PP_DISCOUNT_PURCHASE_ORDER				[DECIMAL] (10,4),
	@PP_TOTAL_PURCHASE_ORDER				[DECIMAL] (10,4),
	-----=====================================================
	@PP_ITEM_ARRAY							NVARCHAR(MAX),
	@PP_QUANTITY_ARRAY						NVARCHAR(MAX),
	@PP_PRICE_ARRAY							NVARCHAR(MAX),
	@PP_TOTAL_ARRAY							NVARCHAR(MAX),
	@PP_K_PO_PRICE_ARRAY					NVARCHAR(MAX),
	-----=====================================================
	@PP_TOTAL_ITEMS							[INT],
	-----=====================================================
	--	PARA BLANKET
	@PP_L_IS_BLANKET						[INT],
	@PP_K_CUSTOMER							[INT],
	@PP_D_PROGRAM							[VARCHAR](500),
	@PP_ANNUAL_VOLUME						[DECIMAL](10,4),
	@PP_GROSS_VEHICLE_AREA					[DECIMAL](10,4),
	-----=====================================================
	@PP_C_INFO_QUOTATION					[VARCHAR](500),
	@PP_TERMS_HEADER						[VARCHAR](500),
	-----=====================================================
	@PP_ADDITIONAL_TAXES_PURCHASE_ORDER		[DECIMAL](10,4)
AS			
DECLARE @VP_MENSAJE				VARCHAR(300) = ''
BEGIN TRANSACTION 
BEGIN TRY
	-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE [dbo].[PG_RN_PURCHASE_ORDER_UPDATE]		@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_HEADER_PURCHASE_ORDER, 
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	END
	-- /////////////////////////////////////////////////////////////////////
--	IF @VP_MENSAJE=''
--		EXECUTE [dbo].[PG_RN_HEADER_PURCHASE_ORDER_UNIQUE]		@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
--																@PP_K_HEADER_PURCHASE_ORDER,@PP_D_HEADER_PURCHASE_ORDER, 
--																@PP_RFC_HEADER_PURCHASE_ORDER,
--																@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE=''
	BEGIN
		IF @PP_K_TERMS<>2
		BEGIN
			SET @PP_TERMS_HEADER=''
		END

		UPDATE	HEADER_PURCHASE_ORDER
		SET		
				--[K_HEADER_PURCHASE_ORDER]			= @PP_K_HEADER_PURCHASE_ORDER,				
				[C_PURCHASE_ORDER]					= @PP_C_PURCHASE_ORDER,					
				-- ============================		= -- ============================
				[F_DATE_PURCHASE_ORDER]				= @PP_F_DATE_PURCHASE_ORDER,				
				[F_REQUIRED_PURCHASE_ORDER]			= @PP_F_REQUIRED_PURCHASE_ORDER,		
				-- ============================		= -- ============================		
				[ISSUED_BY_PURCHASE_ORDER]			= @PP_ISSUED_BY_PURCHASE_ORDER,			
				[REQUIRED_PURCHASE_ORDER]			= @PP_REQUIRED_PURCHASE_ORDER,				
				[K_PLACED_BY]						= @PP_K_PLACED_BY,
				[K_APPROVED_BY]						= @PP_K_APPROVED_BY,
				-- ============================		= -- ============================		
				[K_DELIVERY_TO]						= @PP_K_DELIVERY_TO,
				[D_DELIVERY_TO]						= @PP_D_DELIVERY_TO,
				[CONFIRMING_ORDER_WITH]				= @PP_CONFIRMING_ORDER_WITH,				
				[K_VENDOR]							= @PP_K_VENDOR,							
				-- ============================		= -- ============================		
				[K_TERMS]							= @PP_K_TERMS,								
				[K_CURRENCY]						= @PP_K_CURRENCY,							
				[TAX_RATE]							= (@PP_TAX_RATE/100),							
				-- ============================		= -- ============================		
				[TOTAL_ITEMS]						= @PP_TOTAL_ITEMS,							
				[SUBTOTAL_PURCHASE_ORDER]			= @PP_SUBTOTAL_PURCHASE_ORDER,				
				[IVA_PURCHASE_ORDER]				= @PP_IVA_PURCHASE_ORDER,
				[ADDITIONAL_TAXES_PURCHASE_ORDER]	= @PP_ADDITIONAL_TAXES_PURCHASE_ORDER,					
				[ADDITIONAL_DISCOUNTS_PURCHASE_ORDER]=@PP_DISCOUNT_PURCHASE_ORDER,
				[TOTAL_PURCHASE_ORDER]				= @PP_TOTAL_PURCHASE_ORDER,				
				-- ============================		= -- ============================
				[L_IS_BLANKET]						= @PP_L_IS_BLANKET,
				[C_INFO_QUOTATION]					= @PP_C_INFO_QUOTATION,
				[TERMS_HEADER]						= @PP_TERMS_HEADER,
				-- ============================		= -- ============================
				[F_CAMBIO]							= GETDATE(), 
				[K_USUARIO_CAMBIO]					= @PP_K_USUARIO_ACCION
		WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
		IF @@ROWCOUNT = 0
			BEGIN
				SET @VP_MENSAJE='The HEADER_PURCHASE_ORDER was not updated. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
				RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
			END
	END
		
	IF @VP_MENSAJE=''
	BEGIN
		DELETE 
		FROM	DETAILS_PURCHASE_ORDER
		WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER

		DELETE 
		FROM	DETAILS_BLANKET_PURCHASE_ORDER
		WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
	END

	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE		[dbo].[PG_IN_DETAILS_PURCHASE_ORDER]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															-----=====================================================
															@PP_K_HEADER_PURCHASE_ORDER,
															@PP_ITEM_ARRAY,		@PP_QUANTITY_ARRAY,
															@PP_PRICE_ARRAY,	@PP_TOTAL_ARRAY,	@PP_K_PO_PRICE_ARRAY

		EXECUTE		[dbo].[PG_INUP_DETAILS_BLANKET_PURCHASE_ORDER]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															-----=====================================================
															@PP_K_HEADER_PURCHASE_ORDER,	@PP_L_IS_BLANKET,	
															@PP_K_CUSTOMER,					@PP_D_PROGRAM,					
															@PP_ANNUAL_VOLUME,				@PP_GROSS_VEHICLE_AREA
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [Update] at [HEADER_PURCHASE_ORDER]: ' + @VP_MENSAJE 
	END

	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////	
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / FICHA
-- // PARA ACTUALIZAR EL ENCABEZADO DE LA PO
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_CLOSE_PARTIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_CLOSE_PARTIAL]
GO
--       EXECUTE [dbo].[PG_UP_CLOSE_PARTIAL] 0, 139, 'COMENTARIO DE PRUEBA'
CREATE PROCEDURE [dbo].[PG_UP_CLOSE_PARTIAL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		[INT],
	@PP_C_CLOSURE_PO				NVARCHAR(MAX)
AS			
DECLARE @VP_MENSAJE				VARCHAR(300) = ''
BEGIN TRANSACTION 
BEGIN TRY
	-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE [dbo].[PG_RN_PURCHASE_ORDER_UPDATE]		@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_HEADER_PURCHASE_ORDER, 
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	END
	-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		UPDATE	HEADER_PURCHASE_ORDER
		SET		
				-- ============================	= -- ============================
				[K_STATUS_PURCHASE_ORDER]		=	14,
				-- ============================	= -- ============================
				[F_CAMBIO]						= GETDATE(), 
				[K_USUARIO_CAMBIO]				= @PP_K_USUARIO_ACCION
		WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
		IF @@ROWCOUNT = 0
			BEGIN
				SET @VP_MENSAJE='The STATUS(#14) was not changed. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
				RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
			END
	END
		
	IF @VP_MENSAJE=''
	BEGIN
		INSERT	INTO [PO_PARTIAL_CLOSED_LOG]
		(	[C_PO_PARTIAL_CLOSED_LOG]	,	[K_HEADER_PURCHASE_ORDER]	,
			[K_USUARIO]					,	[F_PO_PARTIAL_CLOSED_LOG]	)
		VALUES
		(	@PP_C_CLOSURE_PO			,	@PP_K_HEADER_PURCHASE_ORDER,
		@PP_K_USUARIO_ACCION			,	GETDATE()					)
		IF @@ROWCOUNT = 0
			BEGIN
				SET @VP_MENSAJE='Comments in LOG was not INSERTED. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
				RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
			END

	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [Update] at [HEADER_PURCHASE_ORDER]: ' + @VP_MENSAJE 
	END

	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////	
GO



-- //////////////////////////////////////////////////////////////
-- // PARA ACTUALIZAR LOS DETALLES DE LA ORDEN DE COMPRA
-- // LA CANTIDAD DE ARTÍCULOS RECIBIDOS.
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_DETAILS_RECEIVED]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_DETAILS_RECEIVED]
GO
 --				EXECUTE [PG_UP_DETAILS_RECEIVED] 0,139,4 , '20/19/31/17/18' , '1/2/3/4/5' , '0/0/0/0/0' , '0/1/2/3/4' , '1/1/1/1/1' , '13'
 CREATE PROCEDURE [dbo].[PG_UP_DETAILS_RECEIVED]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-----=====================================================
	@PP_K_HEADER_PURCHASE_ORDER		INT,
	@PP_ITEM_ARRAY					NVARCHAR(MAX),
	@PP_QUANTITY_ORDER_ARRAY		NVARCHAR(MAX),
	@PP_QUANTITY_RECEI_ARRAY		NVARCHAR(MAX),
	@PP_QUANTITY_PENDI_ARRAY		NVARCHAR(MAX),
	@PP_QUANTITY_PENDO_ARRAY		NVARCHAR(MAX),
	@PP_K_STATUS_PO					INT
	-----=====================================================
AS
DECLARE @VP_MENSAJE				VARCHAR(300) = ''
BEGIN TRANSACTION 
BEGIN TRY
	-----=====================================================					
	DECLARE @VP_STATUS_PO_IN_BD	INT=-1
	DECLARE @VP_DATE_PROMISE	DATE
	-----=====================================================					
	DECLARE @VP_POSICION_ITEM	INT
	DECLARE @VP_POSICION_QTY_OR	INT
	DECLARE @VP_POSICION_QTY_RE	INT
	DECLARE @VP_POSICION_QTY_PE	INT
	DECLARE @VP_POSICION_QTY_PN	INT
	-----=====================================================		
	DECLARE @VP_VALOR_ITEM		VARCHAR(500)
	DECLARE @VP_VALOR_QTY_OR	VARCHAR(500)
	DECLARE @VP_VALOR_QTY_RE	VARCHAR(500)
	DECLARE @VP_VALOR_QTY_PE	VARCHAR(500)
	DECLARE @VP_VALOR_QTY_PN	VARCHAR(500)
	-----=====================================================
	SELECT	@VP_STATUS_PO_IN_BD=K_STATUS_PURCHASE_ORDER,
			@VP_DATE_PROMISE=F_PROMISE_PURCHASE_ORDER
	FROM	HEADER_PURCHASE_ORDER
	WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER

	IF @VP_DATE_PROMISE IS NULL
	BEGIN
		SET	@VP_DATE_PROMISE = GETDATE()
	END

	IF @VP_STATUS_PO_IN_BD<>@PP_K_STATUS_PO
	BEGIN
		--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
		SET @VP_MENSAJE='STATUS [PO] NOT VALID FOR THIS ACTION, VERIFY. [STATUS_IN_BD# '+CONVERT(VARCHAR(10),@VP_STATUS_PO_IN_BD)+']'
		RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
	END

	IF @VP_MENSAJE=''
	BEGIN
		-----=====================================================
		--Colocamos un separador al final de los parametros para que funcione bien nuestro codigo
		SET	@PP_ITEM_ARRAY				= @PP_ITEM_ARRAY		+ '/'
		SET	@PP_QUANTITY_ORDER_ARRAY	= @PP_QUANTITY_ORDER_ARRAY	+ '/'
		SET	@PP_QUANTITY_RECEI_ARRAY	= @PP_QUANTITY_RECEI_ARRAY	+ '/'
		SET	@PP_QUANTITY_PENDI_ARRAY	= @PP_QUANTITY_PENDI_ARRAY	+ '/'
		SET	@PP_QUANTITY_PENDO_ARRAY	= @PP_QUANTITY_PENDO_ARRAY	+ '/'
		
		--Hacemos un bucle que se repite mientras haya separadores, patindex busca un patron en una cadena y nos devuelve su posicion
		WHILE patindex('%/%' , @PP_ITEM_ARRAY) <> 0
		BEGIN
			SELECT @VP_POSICION_ITEM	=	patindex('%/%' , @PP_ITEM_ARRAY		)
			SELECT @VP_POSICION_QTY_OR	=	patindex('%/%' , @PP_QUANTITY_ORDER_ARRAY	)
			SELECT @VP_POSICION_QTY_RE	=	patindex('%/%' , @PP_QUANTITY_RECEI_ARRAY	)
			SELECT @VP_POSICION_QTY_PE	=	patindex('%/%' , @PP_QUANTITY_PENDI_ARRAY	)
			SELECT @VP_POSICION_QTY_PN	=	patindex('%/%' , @PP_QUANTITY_PENDO_ARRAY	)

			--Buscamos la posicion de la primera y obtenemos los caracteres hasta esa posicion
			SELECT @VP_VALOR_ITEM		= LEFT(@PP_ITEM_ARRAY		, @VP_POSICION_ITEM		- 1)
			SELECT @VP_VALOR_QTY_OR		= LEFT(@PP_QUANTITY_ORDER_ARRAY	, @VP_POSICION_QTY_OR	- 1)
			SELECT @VP_VALOR_QTY_RE		= LEFT(@PP_QUANTITY_RECEI_ARRAY	, @VP_POSICION_QTY_RE	- 1)
			SELECT @VP_VALOR_QTY_PE		= LEFT(@PP_QUANTITY_PENDI_ARRAY	, @VP_POSICION_QTY_PE	- 1)
			SELECT @VP_VALOR_QTY_PN		= LEFT(@PP_QUANTITY_PENDO_ARRAY	, @VP_POSICION_QTY_PN	- 1)
		
			DECLARE @VP_TOTAL_PENDIENTE DECIMAL = 0
			DECLARE @VP_TOTAL_RECIBIDA	DECIMAL = 0

					IF @PP_K_STATUS_PO=11
					BEGIN
						SET @VP_TOTAL_PENDIENTE =	CONVERT(DECIMAL,@VP_VALOR_QTY_PE)
						SET @VP_TOTAL_RECIBIDA	=	CONVERT(DECIMAL,(@VP_VALOR_QTY_RE))
					END
					ELSE
					BEGIN
						SET	@VP_TOTAL_RECIBIDA	=	(CONVERT(DECIMAL,(@VP_VALOR_QTY_RE)) + CONVERT(DECIMAL,@VP_VALOR_QTY_PN))
						SET @VP_TOTAL_PENDIENTE =	CONVERT(DECIMAL,@VP_VALOR_QTY_OR) - @VP_TOTAL_RECIBIDA
					END
					
					UPDATE	[DETAILS_PURCHASE_ORDER]			
					SET		[QUANTITY_ORDER]	=	@VP_VALOR_QTY_OR,
							[QUANTITY_RECEIVED]	=	@VP_TOTAL_RECIBIDA,
							[QUANTITY_PENDING]	=	@VP_TOTAL_PENDIENTE
					WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
					AND		[K_ITEM]=@VP_VALOR_ITEM
						
					IF @@ROWCOUNT = 0
						BEGIN
							--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
							SET @VP_MENSAJE='The DETAIL_PURCHASE_ORDER was not updated. [DETAIL#'+CONVERT(VARCHAR(10),@VP_VALOR_ITEM)+']'
							RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						END

			--Reemplazamos lo procesado con nada con la funcion stuff
			SELECT @PP_ITEM_ARRAY		= STUFF(@PP_ITEM_ARRAY		, 1, @VP_POSICION_ITEM , '')
			SELECT @PP_QUANTITY_ORDER_ARRAY	= STUFF(@PP_QUANTITY_ORDER_ARRAY	, 1, @VP_POSICION_QTY_OR  , '')
			SELECT @PP_QUANTITY_RECEI_ARRAY	= STUFF(@PP_QUANTITY_RECEI_ARRAY	, 1, @VP_POSICION_QTY_RE  , '')
			SELECT @PP_QUANTITY_PENDI_ARRAY	= STUFF(@PP_QUANTITY_PENDI_ARRAY	, 1, @VP_POSICION_QTY_PE  , '')
			SELECT @PP_QUANTITY_PENDO_ARRAY	= STUFF(@PP_QUANTITY_PENDO_ARRAY	, 1, @VP_POSICION_QTY_PN  , '')
		END
	-- ///////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		DECLARE @VP_SUMA_PENDIENTES DECIMAL=-1

		SELECT	@VP_SUMA_PENDIENTES=SUM(QUANTITY_PENDING)
		FROM	DETAILS_PURCHASE_ORDER
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER

		IF @VP_SUMA_PENDIENTES IS NULL	OR	@VP_SUMA_PENDIENTES=-1
			BEGIN
				--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
				SET @VP_MENSAJE='The status in HEADER_PURCHASE_ORDER was not updated. [PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
				RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
			END
		
		IF @VP_MENSAJE=''
		BEGIN
			IF @VP_SUMA_PENDIENTES=0			
			BEGIN
				UPDATE	[HEADER_PURCHASE_ORDER]
				SET		[K_STATUS_PURCHASE_ORDER]	= 12,
						[F_RECEIVED_PURCHASE_ORDER]	= GETDATE(),						
						[F_PROMISE_PURCHASE_ORDER]	= @VP_DATE_PROMISE
				WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
			END
			ELSE
			BEGIN
				UPDATE	[HEADER_PURCHASE_ORDER]
				SET		[K_STATUS_PURCHASE_ORDER]	= 13,
						[F_RECEIVED_PURCHASE_ORDER]	= GETDATE(),
						[F_PROMISE_PURCHASE_ORDER]	= @VP_DATE_PROMISE
				WHERE	[K_HEADER_PURCHASE_ORDER]=@PP_K_HEADER_PURCHASE_ORDER
			END
		END

	END
	-- ///////////////////////////////////////////
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	
	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [UPDATE]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / DATE_RECEIVED
-- // PARA ACTUALIZAR LA FECHA DE RECEPCIÓN DE LAS PO
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_DATE_RECEIVED_PO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_DATE_RECEIVED_PO]
GO
--		 EXECUTE [dbo].[PG_UP_DATE_RECEIVED_PO]	0,129,  4,1
CREATE PROCEDURE [dbo].[PG_UP_DATE_RECEIVED_PO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_PO_ARRAY					[NVARCHAR](MAX),
	@PP_F_RECEIVED					DATE
AS
DECLARE @VP_MENSAJE			VARCHAR(500)=''

DECLARE @VP_POSICION_PO		INT
DECLARE @VP_VALOR_PO		VARCHAR(500)

DECLARE @VP_ESTATUS_PO		INT
-- /////////////////////////////////////////////////////////////////////
BEGIN TRANSACTION 
BEGIN TRY
	IF @VP_MENSAJE=''
	--Colocamos un separador al final de los parametros para que funcione bien nuestro codigo
	SET	@PP_PO_ARRAY		= @PP_PO_ARRAY		+ '/'

		--Hacemos un bucle que se repite mientras haya separadores, patindex busca un patron en una cadena y nos devuelve su posicion
	WHILE patindex('%/%' , @PP_PO_ARRAY) <> 0
		BEGIN
			SELECT @VP_POSICION_PO	=	patindex('%/%' , @PP_PO_ARRAY		)

			--Buscamos la posicion de la primera y obtenemos los caracteres hasta esa posicion
			SELECT @VP_VALOR_PO		= LEFT(@PP_PO_ARRAY		, @VP_POSICION_PO		- 1)
			
			-- PRIMERO SE VERIFICA QUE TENGA VALOR LA PO. Y QUE SE ENCUENTRE ACTIVA EN LAS PO
			IF @VP_VALOR_PO<>''
			BEGIN
				SELECT	@VP_ESTATUS_PO=K_STATUS_PURCHASE_ORDER
				FROM	HEADER_PURCHASE_ORDER
				WHERE	K_HEADER_PURCHASE_ORDER=@VP_VALOR_PO
				AND		K_STATUS_PURCHASE_ORDER IN (11)
				AND		L_BORRADO<>1

				IF @@ROWCOUNT = 0
						BEGIN
							--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
							SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] CANNOT UPDATE DATE RECEIVED'
							RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						END			
			END

			--SE IDENTIFICA EL ESTATUS EN EL QUE SE ENCUENTRA Y SE PROCEDE A ACTUALIZAR.
			IF @VP_MENSAJE=''
			BEGIN
				IF @VP_ESTATUS_PO IN (11)
				BEGIN
					--DECLARE @VP_SIGUIENTE_STATUS INT=1
					--SET @VP_SIGUIENTE_STATUS += @VP_ESTATUS_PO + @PP_K_PO_APROBADA
			
					UPDATE HEADER_PURCHASE_ORDER
					SET
							F_PROMISE_PURCHASE_ORDER=@PP_F_RECEIVED
							--K_STATUS_PURCHASE_ORDER=@VP_SIGUIENTE_STATUS
					WHERE	K_HEADER_PURCHASE_ORDER=@VP_VALOR_PO
					AND		L_BORRADO<>1

						IF @@ROWCOUNT = 0
						BEGIN
							--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
							SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] Not UPDATE'
							RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						END													
				END
			END
			--Reemplazamos lo procesado con nada con la funcion stuff
			SELECT @PP_PO_ARRAY		= STUFF(@PP_PO_ARRAY		, 1, @VP_POSICION_PO , '')
		END
	-- ////////////////////////////////////////////////////////////////
	-- ///////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH
-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [UPDATE] at [DATE_RECEIVED]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_VALOR_PO AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / PO
-- // PARA ACTUALIZAR EL ESTATUS DE LA PO DESDE LA PANTALLA DE USUARIO QUE LA GENERA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_ESTATUS_PO_SEND_REVIEW]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_ESTATUS_PO_SEND_REVIEW]
GO
--		 EXECUTE [dbo].[PG_UP_ESTATUS_PO_SEND_REVIEW]	0,129,  6
CREATE PROCEDURE [dbo].[PG_UP_ESTATUS_PO_SEND_REVIEW]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		[INT]
AS
DECLARE @VP_MENSAJE			VARCHAR(500)=''
DECLARE @VP_ESTATUS_PO		INT
-- /////////////////////////////////////////////////////////////////////
BEGIN TRANSACTION 
BEGIN TRY
	IF @VP_MENSAJE=''
	BEGIN
		SELECT	@VP_ESTATUS_PO=K_STATUS_PURCHASE_ORDER
		FROM	HEADER_PURCHASE_ORDER
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
		AND		L_BORRADO<>1

		IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] NOT FOUND'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END			
	END

	IF @VP_MENSAJE=''
	BEGIN
		IF	@VP_ESTATUS_PO NOT IN (1,3,5,8)
		BEGIN
			SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] IN REVIEW'
		END
		ELSE IF @VP_ESTATUS_PO IN (1,3,5,8)
		BEGIN
			SET	@VP_ESTATUS_PO = 2
			GOTO UPDATE_PO
		END
	END

	IF @VP_MENSAJE=''
	BEGIN
UPDATE_PO:
		UPDATE HEADER_PURCHASE_ORDER
		SET
				K_STATUS_PURCHASE_ORDER=@VP_ESTATUS_PO
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER

		IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] Not UPDATE'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END		
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH
-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [UPDATE] at [STATUS_PO]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / PO
-- // PARA ACTUALIZAR EL ESTATUS DE LA PO POR PARTE DE GERENCIA Y FINANZAS(ESTO ANTES DE QUE SE ENVÍE A IMPRIMIR)
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_ESTATUS_PO_MANAGER_DPTO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_ESTATUS_PO_MANAGER_DPTO]
GO
--		 EXECUTE [dbo].[PG_UP_ESTATUS_PO_MANAGER_DPTO]	0,139,  7,1
CREATE PROCEDURE [dbo].[PG_UP_ESTATUS_PO_MANAGER_DPTO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_PO_ARRAY					[NVARCHAR](MAX),
	@PP_K_PO_APROBADA				[INT]
AS
DECLARE @VP_MENSAJE			VARCHAR(500)=''
DECLARE @VP_K_VENDOR		INT

DECLARE @VP_POSICION_PO		INT
DECLARE @VP_VALOR_PO		VARCHAR(500)

DECLARE @VP_ESTATUS_PO		INT
-- /////////////////////////////////////////////////////////////////////
BEGIN TRANSACTION 
BEGIN TRY
	IF @VP_MENSAJE=''
	--Colocamos un separador al final de los parametros para que funcione bien nuestro codigo
	SET	@PP_PO_ARRAY		= @PP_PO_ARRAY		+ '/'

		--Hacemos un bucle que se repite mientras haya separadores, patindex busca un patron en una cadena y nos devuelve su posicion
	WHILE patindex('%/%' , @PP_PO_ARRAY) <> 0
		BEGIN
			SELECT @VP_POSICION_PO	=	patindex('%/%' , @PP_PO_ARRAY		)

			--Buscamos la posicion de la primera y obtenemos los caracteres hasta esa posicion
			SELECT @VP_VALOR_PO		= LEFT(@PP_PO_ARRAY		, @VP_POSICION_PO		- 1)
			
			-- PRIMERO SE VERIFICA QUE TENGA VALOR LA PO. Y QUE SE ENCUENTRE ACTIVA EN LAS PO
			IF @VP_VALOR_PO<>''
			BEGIN
				SELECT	@VP_ESTATUS_PO	=	K_STATUS_PURCHASE_ORDER,
						@VP_K_VENDOR	=	K_VENDOR
				FROM	HEADER_PURCHASE_ORDER
				WHERE	K_HEADER_PURCHASE_ORDER=@VP_VALOR_PO
				AND		K_STATUS_PURCHASE_ORDER IN (2,4,7)
				AND		L_BORRADO<>1

				IF @@ROWCOUNT = 0
						BEGIN
							--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
							SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] CANNOT UPDATE'
							RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						END			
			END

			--SE IDENTIFICA EL ESTATUS EN EL QUE SE ENCUENTRA Y SE PROCEDE A ACTUALIZAR.
			IF @VP_MENSAJE=''
			BEGIN
				IF @VP_ESTATUS_PO >= 10
				BEGIN
					SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] Not UPDATE. STATUS NOT VALID FOR THIS ACTION, VERIFY.'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.					
				END
				ELSE IF @VP_ESTATUS_PO IN (2,4,7)
				BEGIN
					DECLARE @VP_SIGUIENTE_STATUS INT=1
					SET @VP_SIGUIENTE_STATUS += @VP_ESTATUS_PO + @PP_K_PO_APROBADA
			
					UPDATE HEADER_PURCHASE_ORDER
					SET
							K_STATUS_PURCHASE_ORDER=@VP_SIGUIENTE_STATUS
					WHERE	K_HEADER_PURCHASE_ORDER=@VP_VALOR_PO
					AND		L_BORRADO<>1

						IF @@ROWCOUNT = 0
						BEGIN
							--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
							SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] Not UPDATE'
							RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						END													
				END
			END

			-- SI EL ESTATUS SE ENCUENTRA EN (9) QUE ES APROBADO, SE ENVIA EL CORREO AL PROVEEDOR.
			IF @VP_MENSAJE=''
			BEGIN
				IF @VP_SIGUIENTE_STATUS = 9
				BEGIN
					DECLARE @VP_RECIPIENTS	NVARCHAR(MAX)	= '';
					DECLARE @VP_FILE_PATH  NVARCHAR(MAX)	=''	;
					DECLARE @VP_PO_INT INT;
					DECLARE @VP_SUBJECT NVARCHAR(MAX) ;
					DECLARE @VP_BODY_HTML  NVARCHAR(MAX) ;
					DECLARE @VP_ID_MAIL INT;
					DECLARE @VP_SENT_STATUS VARCHAR(500);
					----================================================================				
								
  					SET @VP_PO_INT = CAST(@VP_VALOR_PO AS INT)

					----================================================================
					-- CUANDO SE PONGA EN PRODUCTIVO SE DEBE QUITAR EL COMENTARIO A ESTA LÍNEA
					-- PARA QUE SE ENVIE A TODOS LOS CONTACTOS.					
					--	SELECT  @VP_RECIPIENTS	=	@VP_RECIPIENTS + ';' + EMAIL_1 + ';' + EMAIL_2
					--								FROM	COMPRAS.dbo.VENDOR
					--								WHERE   K_VENDOR = @VP_K_VENDOR
					----================================================================
					IF @PP_K_SISTEMA_EXE=0
					BEGIN
						SET @VP_FILE_PATH = '\\10.1.1.5\documents\Common\COMPRAS\REPORTES\POT_'+ CONVERT(VARCHAR(10),FORMAT(@VP_PO_INT,'000000')) +'.PDF'
					END					
					ELSE
					--IF @PP_K_SISTEMA_EXE=0
					BEGIN
						-- USUARIO DEFAULT DE COMPRAS A DONDE SE ENVIARÁ EL CORREO.
						SET @VP_RECIPIENTS = 'FABIOLAG@PEARLLEATHER.COM.MX'						
						SET @VP_FILE_PATH = '\\10.1.1.5\documents\Common\COMPRAS\REPORTES\PO_'+ CONVERT(VARCHAR(10),FORMAT(@VP_PO_INT,'000000')) +'.PDF'  
					END
					
					----================================================================
					-- SET @VP_RECIPIENTS = SUBSTRING(@VP_RECIPIENTS,2,LEN(@VP_RECIPIENTS))						
					----================================================================
					IF @PP_K_SISTEMA_EXE=0
					BEGIN
						SET @VP_SUBJECT = 'PEARL LEATHER [POT#' + CONVERT(VARCHAR(10),FORMAT(@VP_PO_INT,'000000')) +']'--CONVERT(VARCHAR(10),FORMAT(@VP_VALOR_PO,'000000'))+']'					
					END
					ELSE
					BEGIN
						SET @VP_SUBJECT = 'PEARL LEATHER [PO#' + CONVERT(VARCHAR(10),FORMAT(@VP_PO_INT,'000000')) +']'--CONVERT(VARCHAR(10),FORMAT(@VP_VALOR_PO,'000000'))+']'					
					END
					SET @VP_BODY_HTML =  
					N'<p style="font-size:12.0pt;font-family:"Calisto MT",serif;color:#262626">'+
					N'Buen día, <br><br>'+
					N'Se envía orden de compra, favor de realizar el seguimiento correspondiente para la entrega.<br>'+
					N'Favor de confirmar de recibido y fecha de entrega estimada.<br><br>'+
					N'Saludos.<br> == = == = == = == = == = == = == = == = == = == = == = == = == = == = ==<br>'+
					N'Good day, <br><br>'+
					N'Purchase order is sent, please track it for delivery.<br>'+
					N'Please confirm receipt and estimated delivery date.<br><br>'+
					N'Regards.<br> </p> <p>'+
					N'<span style="font-size:12.0pt;font-family:"Cambria",serif;color:#943634"><b>Fabiola Gerardo Arévalo | Compras</b></span><br>'+
					N'<span style="font-family:"Cambria",serif;color:#D99594"><b>Dirección:</b></span>'+
					N'<span style="font-family:"Cambria",serif;color:#D99594">Av. Rosa Maria Y. Fuentes 7050-A <b>|C.P.</b> 32320</span></br>'+
					N'<span style="font-family:"Cambria",serif;color:#D99594"><b>Tel.</b>656-892-5800<b>|Ext:</b>121'+
					N'<b>|Cel.</b> 656-103-4020<o:p></o:p></span><br><br></p>'+
					N'<p><span style="font-size:10.0pt;font-family:"Cambria",serif;color:#943634"><b><u>RECEPCION DE MATERIAL <b>|</b> RECEIPT OF MATERIAL</u></b></p>'+
					N'<p><span style="font-size:8.0pt;font-family:"Cambria",serif;color:#943634"><b>Lunes a Viernes | Monday to Friday: 7am -9am, 10am -2pm y 4pm -5:30pm</b></span></p>'

					--N'<p style="color:blue; font-size:20px">	Buen día:<br>' +
					--N'<tab1 style="white-space:pre">	</tab1>	Se adjunta orden de compra para que sea procesada a la brevedad.<br> Saludos, Gracias!</p>' +					
					--N'<p style="color:black; font-size:20px"> == = == = == = == = == = == </p>'+					
					--N'<p style="color:blue; font-size:20px">	Good Day:<br>'+
					--N'<tab1 style="white-space:pre">	</tab1>	A purchase order is attached to be processed promptly.<br> Best regards, thanks!</p>'+					
					--N'<p style="color:black; font-size:20px">== = == = == = == = == = == </p>'+					
					--N'<p><span style="color:maroon; font-size:20px"><strong> Fabiola Gerardo Arévalo | Compras </strong></span><br>'+
					--N'<span style="color:green; font-size:15px"> Dirección: Av. Rosa Maria Y. Fuentes 7050-A |C.P.32320 <br>'+
					--N'Tel. 656-892-5800|Ext: 121|Cel. 656-103-4020 </span></p>'+					
					--N'<p><span style="color:navy; font-size:15px"><strong> RECEPCION DE MATERIAL </strong></span><br>'+					
					--N'<span style="color:black; font-size:15px"> Lunes a Viernes 7am -9am, 10am -2pm y 4pm -5:30pm </span></p>'				  								
					
					EXEC msdb.dbo.sp_send_dbmail @recipients=@VP_RECIPIENTS,
					@copy_recipients = 'ALEJANDROD@PEARLLEATHER.COM.MX',
					@subject = @VP_SUBJECT,
					@body = @VP_BODY_HTML,  
					@body_format = 'HTML', 
					@file_attachments = @VP_FILE_PATH, --EL ARCHIVO A ENVIAR DEBE ESTAR EN EL MISMO (SERVIDOR, EQUIPO) QUE SE TIENE INSTALADO EL SQLSERVER
					@mailitem_id = @VP_ID_MAIL OUTPUT;

					--SELECT	@VP_SENT_STATUS = sent_status						-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
					--FROM	msdb.dbo.sysmail_allitems								-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
					--WHERE	mailitem_id = @VP_ID_MAIL								-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
																					-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
					--IF UPPER(@VP_SENT_STATUS)='SENT'								-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
					--BEGIN															-- EL CORREO TARDA TIEMPO EN ENVIARLO, SE ACTUALIZARA DE OTRA MANERA.
						UPDATE	HEADER_PURCHASE_ORDER
						SET		K_STATUS_PURCHASE_ORDER=11
						WHERE	K_HEADER_PURCHASE_ORDER=@VP_PO_INT

						----IF @@ROWCOUNT = 0
						----BEGIN
						----	--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
						----	SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] Not sent mail, verify recipients and resend...'
						----	RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
						----END	
						
						-- QUITAR COMENTARIO CUANDO SE VALIDE EL CUERPO DEL MENSAJE
						--EXECUTE [dbo].[PG_PR_ENVIAR CORREO]	0,139,  7
					--END

				END
			END

			--Reemplazamos lo procesado con nada con la funcion stuff
			SELECT @PP_PO_ARRAY		= STUFF(@PP_PO_ARRAY		, 1, @VP_POSICION_PO , '')
		END
	-- ////////////////////////////////////////////////////////////////
	-- ///////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH
-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [UPDATE] at [STATUS_PO]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_VALOR_PO AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / PO
-- // PARA ACTUALIZAR EL ESTATUS DE LA PO POR PARTE DE GERENCIA Y FINANZAS(ESTO ANTES DE QUE SE ENVÍE A IMPRIMIR)
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_PR_ENVIAR CORREO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_PR_ENVIAR CORREO]
GO
--		 EXECUTE [dbo].[PG_PR_ENVIAR CORREO]	0,139,  7
CREATE PROCEDURE [dbo].[PG_PR_ENVIAR CORREO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@VP_PO_INT						[INT]
AS
DECLARE @VP_MENSAJE			VARCHAR(500)=''
DECLARE @VP_ESTATUS_PO		INT
-- /////////////////////////////////////////////////////////////////////
BEGIN TRANSACTION 
BEGIN TRY
	SELECT	@VP_ESTATUS_PO	=	K_STATUS_PURCHASE_ORDER
	FROM	HEADER_PURCHASE_ORDER
	WHERE	K_HEADER_PURCHASE_ORDER=@VP_PO_INT
	AND		L_BORRADO<>1
	
	IF NOT (@VP_ESTATUS_PO IS NULL) OR @VP_ESTATUS_PO=9
	BEGIN
		DECLARE @VP_RECIPIENTS	NVARCHAR(MAX)	= '';
		--DECLARE @VP_FILE_PATH  NVARCHAR(MAX)	=''	;
		--DECLARE @VP_PO_INT INT;

		DECLARE @VP_SUBJECT NVARCHAR(MAX) ;
		DECLARE @VP_BODY_HTML  NVARCHAR(MAX) ;
		DECLARE @VP_ID_MAIL INT;
		DECLARE @VP_SENT_STATUS VARCHAR(500);
		----================================================================
		--	PARA PRUEBAS
		--SELECT	@VP_RECIPIENTS	=	@VP_RECIPIENTS + ';' + CORREO_GERENTE.CORREO_USUARIO_PEARL + ';' +
		--												   CORREO_USUARIO.CORREO_USUARIO_PEARL
		SELECT	@VP_RECIPIENTS	=	@VP_RECIPIENTS + ';' + CORREO_USUARIO.CORREO_USUARIO_PEARL
		FROM	HEADER_PURCHASE_ORDER
		LEFT JOIN BD_GENERAL.DBO.USUARIO_PEARL	AS CORREO_USUARIO ON HEADER_PURCHASE_ORDER.K_USUARIO_ALTA=CORREO_USUARIO.K_USUARIO_PEARL
		--LEFT JOIN BD_GENERAL.DBO.USUARIO_PEARL	AS CORREO_GERENTE ON HEADER_PURCHASE_ORDER.K_APPROVED_BY =CORREO_GERENTE.K_EMPLEADO_PEARL
		WHERE	K_HEADER_PURCHASE_ORDER=@VP_PO_INT
					
		----================================================================
		SET @VP_SUBJECT = 'APROBADA [PO#' + CONVERT(VARCHAR(10),FORMAT(@VP_PO_INT,'000000')) +']'
		
		SET @VP_BODY_HTML =  
		N'<p style="color:blue; font-size:20px">	Buen día:<br>' +
		N'La orden de compra ha sido aprobada por Gerencia de Planta.<br>'+
		N'Si el proveedor cuenta con dirección de correo electrónico agregada, <br>'+
		N'el formato será enviado automáticamente al destinatario, en caso contrario, <br>'+
		N'el departamento de finanzas le dará seguimiento. <br></p>'+
		
		N'<p><span style="color:maroon; font-size:20px"><strong> Fabiola Gerardo Arévalo | Compras </strong></span><br>'+
		N'<span style="color:green; font-size:15px"> Dirección: Av. Rosa Maria Y. Fuentes 7050-A |C.P.32320 <br>'+
		N'Tel. 656-892-5800|Ext: 121|Cel. 656-103-4020 </span></p>'+
		N'<p><span style="color:navy; font-size:15px"><strong> RECEPCION DE MATERIAL </strong></span><br>'+
		N'<span style="color:black; font-size:15px"> Lunes a Viernes 7am -9am, 10am -2pm y 4pm -5:30pm </span></p>'					  								
	
			EXEC msdb.dbo.sp_send_dbmail @recipients=@VP_RECIPIENTS,
			--	@copy_recipients = 'ALEJANDROD@PEARLLEATHER.COM.MX',
			@subject = @VP_SUBJECT,
			@body = @VP_BODY_HTML,  
			@body_format = 'HTML', 
			--@file_attachments = @VP_FILE_PATH, --EL ARCHIVO A ENVIAR DEBE ESTAR EN EL MISMO (SERVIDOR, EQUIPO) QUE SE TIENE INSTALADO EL SQLSERVER
			@mailitem_id = @VP_ID_MAIL OUTPUT;

			SELECT	@VP_SENT_STATUS = sent_status
			FROM	msdb.dbo.sysmail_allitems
			WHERE	mailitem_id = @VP_ID_MAIL

			--IF UPPER(@VP_SENT_STATUS)='SENT'
			--BEGIN
			--	UPDATE	HEADER_PURCHASE_ORDER
			--	SET		K_STATUS_PURCHASE_ORDER=11
			--	WHERE	K_HEADER_PURCHASE_ORDER=@VP_PO_INT

				--IF @@ROWCOUNT = 0
				--BEGIN
				--	--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
				--	SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@VP_VALOR_PO)+'] Not sent mail, verify recipients and resend...'
				--	RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				--END	
			--END
		END
	-- ////////////////////////////////////////////////////////////////
	-- ///////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH
-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [SEND MAIL] at [USERS PEARL]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_PO_INT AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE / PO
-- // PARA ACTUALIZAR EL ESTATUS DE LA PO DESDE LA PANTALL DE USUARIO QUE LA GENERA
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_ESTATUS_PO_SEND_PRINT]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_ESTATUS_PO_SEND_PRINT]
GO
--		 EXECUTE [dbo].[PG_UP_ESTATUS_PO_SEND_PRINT]	0,129,  6
CREATE PROCEDURE [dbo].[PG_UP_ESTATUS_PO_SEND_PRINT]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		[INT]
AS
DECLARE @VP_MENSAJE			VARCHAR(500)=''
DECLARE @VP_ESTATUS_PO		INT
-- /////////////////////////////////////////////////////////////////////
BEGIN TRANSACTION 
BEGIN TRY
	IF @VP_MENSAJE=''
	BEGIN
		SELECT	@VP_ESTATUS_PO=K_STATUS_PURCHASE_ORDER
		FROM	HEADER_PURCHASE_ORDER
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
--		AND		K_STATUS_PURCHASE_ORDER IN (6,7)
		AND		L_BORRADO<>1

		IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] NOT AVAILABLE'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END			
	END

	IF @VP_MENSAJE=''
	BEGIN
		IF	@VP_ESTATUS_PO NOT IN (6,7)
		BEGIN
			SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] NOT AVAILABLE FOR PRINT'
		END
		ELSE
		BEGIN
			IF @VP_ESTATUS_PO=6
			BEGIN
				SET	@VP_ESTATUS_PO += 1
			END
			GOTO UPDATE_PO
		END
	END

	IF @VP_MENSAJE=''
	BEGIN
UPDATE_PO:
		UPDATE HEADER_PURCHASE_ORDER
		SET
				K_STATUS_PURCHASE_ORDER=@VP_ESTATUS_PO
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER

		IF @@ROWCOUNT = 0
				BEGIN
					--RAISERROR (@VP_ERROR_1, 16, 1 ) --MENSAJE - Severity -State.
					SET @VP_MENSAJE='[PO#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+'] Not UPDATE'
					RAISERROR (@VP_MENSAJE, 16, 1 ) --MENSAJE - Severity -State.
				END		
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	/* Ocurrió un error, deshacemos los cambios*/ 
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH
-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [UPDATE] at [STATUS_PO]: ' + @VP_MENSAJE 
	END
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	EXECUTE [dbo].[PG_DL_HEADER_PURCHASE_ORDER] 0,139,380,2,2
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_DL_HEADER_PURCHASE_ORDER]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_DL_HEADER_PURCHASE_ORDER]
GO
CREATE PROCEDURE [dbo].[PG_DL_HEADER_PURCHASE_ORDER]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_HEADER_PURCHASE_ORDER		INT
AS
DECLARE @VP_MENSAJE				VARCHAR(300) = ''
BEGIN TRANSACTION 
BEGIN TRY
--/////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN
		EXECUTE [dbo].[PG_RN_PURCHASE_ORDER_DELETE]		@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_HEADER_PURCHASE_ORDER, 
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	END
	--////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
	BEGIN		
		UPDATE	HEADER_PURCHASE_ORDER
		SET		
				[L_BORRADO]				= 1,
				-- ====================
				[F_BAJA]				= GETDATE(), 
				[K_USUARIO_BAJA]		= @PP_K_USUARIO_ACCION
		WHERE	K_HEADER_PURCHASE_ORDER=@PP_K_HEADER_PURCHASE_ORDER
		IF @@ROWCOUNT = 0
			BEGIN
				SET @VP_MENSAJE='The HEADER_PURCHASE_ORDER was not updated. [HEADER_PURCHASE_ORDER#'+CONVERT(VARCHAR(10),@PP_K_HEADER_PURCHASE_ORDER)+']'
			END
	END
-- /////////////////////////////////////////////////////////////////////
COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
	DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
	SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR:// ' + @VP_ERROR_TRANS
END CATCH	

	-- /////////////////////////////////////////////////////////////////////	
	IF @VP_MENSAJE<>''
	BEGIN
		SET		@VP_MENSAJE = 'Not is possible [Update] at [HEADER_PURCHASE_ORDER]: ' + @VP_MENSAJE 
	END

	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_HEADER_PURCHASE_ORDER AS CLAVE
	-- //////////////////////////////////////////////////////////////
	
	-- //////////////////////////////////////////////////////////////	
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
/*
-- USUARIOS A LOS QUE SE LES BRINDÓ ACCESO AL SISTEMA
K_		D_USUARIO			D_CORREO
87		DIANA NAVARRETE			
131		JESUS TORRES		XXXX			embarques1@pearlleather.com.mx		--- OK
111		ADRIANA IBARRA		
132		TERESA JIMENEZ		XXXX			-- FALTA GENERAR CORREO
142		ALBA JAQUEZ			
64		LEONOR HERNANDEZ	
145		DULCE IVETH COBOS	
150		ABRHAM REZA			Abrahamr@pearlleather.com.mx		(12210)			--- OK
57		FABIOLA GERARDO		
89		VIVIANA CHAVEZ		
139		ADELAROSA
144		FESTEBAN
41		RAFAELF
115		SONIA ORTIZ			
125		IRIS ESTRADA		
151		EDITH MONTELLANO	edithm@pearlleather.com.mx			(10528)			--- OK
42		OMAR DECENA
47		MIGUEL CARRASCO
56		MANUEL GARCIA
44		GUILLERMO MATA
60		ADRIANA DE LA REE
62		PATRICIA CHAVEZ
*/


--	dianan		Facturas1
--	adrianai	12345
--	dulcec		Password1
--	irise		12345
--	marios		12345

--	omard		12340
--	miguelc		Dalica9905
--	MANUELG		Mangar83

--	SELECT K_USUARIO_PEARL, D_USUARIO_PEARL, PASSWORD_USUARIO_PEARL,K_USUARIO_DEPARTAMENTO,K_EMPLEADO_PEARL FROM BD_GENERAL.DBO.USUARIO_PEARL

--	select * from STATUS_PURCHASE_ORDER