
USE DATA_02
			
			
SELECT * FROM IMITMIDX_SQL WHERE LTRIM(RTRIM(item_no)) LIKE 'F___DX9'

select * from HIDESHDR_SQL   
 --inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
 WHERE TDATE >= '20200901' AND TDATE<= '20200903'
 ORDER BY TDATE, TYPE, COLOR

 DECLARE @VP_TOTAL_HIDE INT, @VP_TOTAL_SQF DECIMAL(13,4)
 SELECT	@VP_TOTAL_HIDE	= SUM(CONVERT(INT,THIDES)),
									@VP_TOTAL_SQF	= SUM(CONVERT(DECIMAL(13,2),TAREA))
							FROM HIDESHDR_SQL   
							WHERE LTRIM(RTRIM(TDATE)) =  LTRIM(RTRIM('20200902'))
							AND TYPE ='WU9 NAPPA'
SELECT @VP_TOTAL_HIDE, @VP_TOTAL_SQF

 select /*TDATE, TYPE, COLOR,*/ SUM(CONVERT(DECIMAL(13,4),THIDES)) AS THIDES,
 SUM(CONVERT(DECIMAL(13,4),TAREA)) AS TOTAL_SQF
 from HIDESHDR_SQL   
 WHERE TDATE = '20200902' --AND LDATE<= '20200903'
 AND TYPE = 'WU9 NAPPA'
 GROUP BY TDATE,TYPE, COLOR
 ORDER BY LDATE,TYPE, COLOR

  select SUM(CONVERT(DECIMAL(13,4),TAREA)) AS TOTAL_SQF 
 from HIDESHDR_SQL   
 WHERE LDATE >= '20200901' AND LDATE<= '20200903'
 --GROUP BY LDATE,TYPE, COLOR
 --ORDER BY LDATE,TYPE, COLOR

 select TYPE, SUBSTRING(CLOT,1,7) AS CLOT, SUM(CONVERT(DECIMAL(13,4),THIDES)) AS TOTAL_SQF , SUM(CONVERT(DECIMAL(13,4),TAREA)) AS TOTAL_SQF 
 from HIDESHDR_SQL   
 WHERE LDATE >= '20200901' AND LDATE<= '20200903'
 GROUP BY TYPE, SUBSTRING(CLOT,1,7) 
 --ORDER BY LDATE,TYPE, COLOR

 SELECT SUBSTRING('33461',1,(LEN('33461') - 1))

--AND	LTRIM(RTRIM(PLOT)) = '401111' 
 --AND LTRIM(RTRIM(HIDE))  IN ('0037')
 --AND PCOLOR = 'FWLCPX7'


 select * from pf_schst where type='e' and n_emb='1' and cdate2='20200922'











