DECLARE @VP_CU_K_HEADER			INT
DECLARE @VP_CU_K_DETALLE		INT
DECLARE @VP_CONTADOR			INT =1
DECLARE @VP_MENSAJE				NVARCHAR(MAX)


BEGIN TRANSACTION
BEGIN TRY

	DECLARE CU_UNIFICAR_PO	CURSOR LOCAL FOR	

			SELECT		K_HEADER_PURCHASE_ORDER, K_DETAILS_PURCHASE_ORDER 
			FROM		DETAILS_PURCHASE_ORDER
			WHERE		K_HEADER_PURCHASE_ORDER IN (78)
			ORDER BY	K_HEADER_PURCHASE_ORDER	
			
		OPEN			CU_UNIFICAR_PO
		FETCH NEXT FROM CU_UNIFICAR_PO INTO		@VP_CU_K_HEADER,	@VP_CU_K_DETALLE
		WHILE @@FETCH_STATUS = 0			
		BEGIN
		
				UPDATE	[DETAILS_PURCHASE_ORDER]
				SET
						[K_HEADER_PURCHASE_ORDER]	=	78,
						[K_DETAILS_PURCHASE_ORDER]	=	@VP_CONTADOR

				WHERE	[K_HEADER_PURCHASE_ORDER]	=	@VP_CU_K_HEADER
				AND		[K_DETAILS_PURCHASE_ORDER]	=	@VP_CU_K_DETALLE

					IF @@ROWCOUNT = 0
					BEGIN
						RAISERROR ('NO SE ACTULIZÓ EL REGISTRO', 16, 1 ) --MENSAJE - Severity -State.
					END

				SET @VP_CONTADOR=@VP_CONTADOR+1


		FETCH NEXT FROM CU_UNIFICAR_PO INTO		@VP_CU_K_HEADER,	@VP_CU_K_DETALLE
		END
		CLOSE		CU_UNIFICAR_PO
		DEALLOCATE	CU_UNIFICAR_PO

COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	--	OCURRIÓ UN ERROR, DESHACEMOS LOS CAMBIOS
	--ROLLBACK TRANSACTION
	DECLARE @ErrorMessage NVARCHAR(4000);
	SET @ErrorMessage = ERROR_MESSAGE() 
	SET @VP_MENSAJE = 'ERROR: // ' + @ErrorMessage
END CATCH


			--		SELECT		*	--K_HEADER_PURCHASE_ORDER, K_DETAILS_PURCHASE_ORDER 
			--		FROM		DETAILS_PURCHASE_ORDER
			--		WHERE		K_HEADER_PURCHASE_ORDER IN (78,79,80,82,84,85,92)
			--		ORDER BY	K_DETAILS_PURCHASE_ORDER


			-- SELECT * FROM DETAILS_PURCHASE_ORDER
			-- WHERE		K_HEADER_PURCHASE_ORDER IN (1)
			-- ORDER BY	K_DETAILS_PURCHASE_ORDER
			

	
	--WHILE @VP_CONTADOR<61
	--	BEGIN

	--		INSERT INTO HEADER_PURCHASE_ORDER_TEMP
	--				(	[K_PO_TEMPORAL]		)
	--		VALUES	
	--				--(	'T'+@PP_K_PO_TEMPORAL	)
	--				(	@VP_CONTADOR	)
		
	--		SET @VP_CONTADOR=@VP_CONTADOR+1
	--	END